window.BANKS = window.BANKS || {};
window.BANKS.final1 = {
  title: "Final Mock Exam 1 — AI-901 (full syllabus)",
  minutes: 60,
  questions: [
    // ===== EASY (11) =====
    {q:"Which option correctly describes the two AI-901 skill areas and their weights?",
     o:["Identify AI concepts and capabilities (~40%); Implement AI solutions with Microsoft Foundry (~60%)",
        "Networking (~50%); Databases (~50%)",
        "Only responsible AI is examined",
        "Coding in C# (~90%); theory (~10%)"],
     a:0, d:1,
     x:"The exam measures AI concepts/capabilities at roughly 40% and Foundry implementation at roughly 60%."},
    {q:"Generative AI is best described as:",
     o:["Using a language model to create original content in response to a prompt",
        "A retrieval system for stored answers",
        "A replacement for all databases",
        "An old technique superseded by machine learning"],
     a:0, d:1,
     x:"Generative AI creates original content — text, images, code — from prompts via language models."},
    {q:"Within a tenant, what does an Azure subscription provide?",
     o:["A billing boundary","A security boundary","A DNS namespace","A GPU cluster"],
     a:0, d:1,
     x:"Subscriptions are billing boundaries; the tenant is the security boundary."},
    {q:"An AI application that performs tasks on behalf of a user is:",
     o:["An agent","A resource lock","A blob container","A subnet"],
     a:0, d:1,
     x:"That is the definition of an AI agent."},
    {q:"Which principle of responsible AI concerns making an AI system's purpose and limitations understandable?",
     o:["Transparency","Fairness","Privacy & security","Inclusiveness"],
     a:0, d:1,
     x:"Transparency = users can understand what the system does, how it behaves, and its limits."},
    {q:"Breaking text into words or word-parts for analysis is called:",
     o:["Tokenization","Diarization","Vectorization of pixels","Prosody"],
     a:0, d:1,
     x:"Tokenization splits text into analyzable units (tokens)."},
    {q:"Converting text into an audio waveform of speech is:",
     o:["Speech synthesis (TTS)","Speech recognition (STT)","OCR","NER"],
     a:0, d:1,
     x:"TTS synthesizes speech from text; STT does the reverse."},
    {q:"Which vision task outputs bounding boxes with class labels?",
     o:["Object detection","Image classification","Semantic segmentation","Summarization"],
     a:0, d:1,
     x:"Object detection localizes each object with a box and label."},
    {q:"OCR converts:",
     o:["Images of text into machine-readable text","Text into images","Audio into text","JSON into XML"],
     a:0, d:1,
     x:"Optical character recognition reads text out of images/documents."},
    {q:"In a Foundry project, models, agents, tools and ______ are the four asset types.",
     o:["Knowledge","Firewalls","Queues","Certificates"],
     a:0, d:1,
     x:"Knowledge manages the data sources that ground agents."},
    {q:"An endpoint in Foundry is:",
     o:["An HTTPS address applications call to reach a deployed model or service",
        "A physical network port",
        "A storage account",
        "The model's training data"],
     a:0, d:1,
     x:"Endpoints are the HTTP entry points for models and services, authenticated by key or Entra ID token."},
    // ===== MODERATE (11) =====
    {q:"A car-safety model is stress-tested across weather, lighting and sensor-failure conditions before release. Which responsible AI principle?",
     o:["Reliability & safety","Inclusiveness","Transparency","Accountability"],
     a:0, d:2,
     x:"Rigorous testing to ensure safe, correct operation within defined limits is reliability & safety."},
    {q:"Which THREE things configure generative model behavior at request time?",
     o:["Instructions (system prompt), user input, and parameters such as temperature",
        "Region, VM size, disk type",
        "Tenant, subscription, resource group",
        "Filters, feature maps, flattening"],
     a:0, d:2,
     x:"System prompt, user prompt, and parameters are the three behavior levers."},
    {q:"What is an embedding?",
     o:["A vector representation of a token capturing semantic meaning",
        "A compressed image",
        "An encrypted key",
        "A duplicate word"],
     a:0, d:2,
     x:"Embeddings place tokens in a multidimensional vector space where similar meanings are near each other."},
    {q:"Which deployment consideration caps a model's tokens-per-minute throughput?",
     o:["Rate limits","Guardrails","Version","Deployment type"],
     a:0, d:2,
     x:"Rate limits define maximum TPM; exceeding them causes throttling."},
    {q:"Which statistical technique scores a term by frequency in one document relative to the whole collection?",
     o:["TF-IDF","Bag-of-Words","TextRank","Word2Vec"],
     a:0, d:2,
     x:"TF-IDF balances local term frequency against corpus-wide document frequency."},
    {q:"In speech recognition, phonemes are produced by the ______ model and turned into probable word sequences by the ______ model.",
     o:["acoustic; language","language; acoustic","linguistic; prosody","waveform; encoder"],
     a:0, d:2,
     x:"Acoustic modeling maps audio features to phonemes; language modeling selects the probable words."},
    {q:"Which statement about the Foundry model playground is TRUE?",
     o:["It lets you test prompts and settings interactively, which you can then reuse in code",
        "It removes the need to deploy models",
        "It writes production apps automatically",
        "It is only available to administrators"],
     a:0, d:2,
     x:"The playground is the experimentation surface; deployment and APIs are still required for apps."},
    {q:"A multimodal prompt contains which content parts?",
     o:["input_text and input_image parts in one content array",
        "Two separate exam sessions",
        "Only audio parts",
        "A CSV attachment"],
     a:0, d:2,
     x:"Multimodal requests mix text and image parts in a single message's content array."},
    {q:"What does an analyzer do in Azure Content Understanding?",
     o:["Defines how content is processed and what structured data is returned",
        "Stores extracted data in a database",
        "Converts JSON to prose",
        "Encrypts documents"],
     a:0, d:2,
     x:"Analyzers (predefined or custom) define processing behavior and the output schema."},
    {q:"Which authentication options secure a Foundry endpoint call?",
     o:["An API key or a Microsoft Entra ID token",
        "A CAPTCHA",
        "An SMS to the admin",
        "No authentication is supported"],
     a:0, d:2,
     x:"Endpoints accept an authorization key or an Entra ID token."},
    {q:"Azure Language differs from prompting a general-purpose model because it provides:",
     o:["Deterministic, structured output with confidence scores",
        "More creative responses",
        "Combined multi-task natural-language replies",
        "Image analysis"],
     a:0, d:2,
     x:"Azure Language is the deterministic, production-oriented route; LLM prompting is flexible but probabilistic."},
    // ===== HARD (23) =====
    {q:"A hiring tool underrates candidates who attended evening programs, which correlates with socioeconomic status. Fixing the training data addresses which principle, and why?",
     o:["Fairness — the system must treat all groups equitably and avoid proxy bias",
        "Transparency — the model must be documented",
        "Privacy — evening data is private",
        "Reliability — the servers must stay up"],
     a:0, d:3,
     x:"Bias via correlated proxies is a fairness failure; equitable treatment requires removing such bias."},
    {q:"Which Azure structure should a company use to give its AI experiments a separate invoice from production, under one identity system?",
     o:["Same tenant, two subscriptions","Two tenants","One subscription, two resource groups","One resource group, two regions"],
     a:0, d:3,
     x:"One tenant preserves shared identity (Entra ID); separate subscriptions split billing."},
    {q:"In the Project API snippet — a=project.agents.get('x'); c=project.get_openai_client(); r=c.responses.create(...) — what has happened after the FIRST two lines only?",
     o:["The agent definition was fetched and a client created; no prompt has been sent yet",
        "The prompt was answered twice",
        "The agent was deleted",
        "The model was retrained"],
     a:0, d:3,
     x:"Only responses.create() submits a prompt; the first lines are setup."},
    {q:"Your model gives perfect answers at temperature 0.2 but the business wants 'more variety' in creative taglines. What is the correct adjustment and trade-off?",
     o:["Raise temperature — more varied/creative output, at the cost of predictability",
        "Lower temperature further — more variety",
        "Increase rate limits — more creativity",
        "Add guardrails — more randomness"],
     a:0, d:3,
     x:"Temperature controls randomness: higher = more variety, less determinism."},
    {q:"Attention in a transformer enables which concrete behavior?",
     o:["The same word is interpreted differently depending on surrounding tokens",
        "Faster disk writes",
        "Automatic translation of prompts",
        "Image compression"],
     a:0, d:3,
     x:"Attention encodes each token's relationships with context, making meaning context-sensitive."},
    {q:"A regulated bank requires: PII redacted deterministically, THEN flexible summarization of the redacted text. Choose the correct two-stage design:",
     o:["Azure Language recognize_pii_entities → general-purpose model summarization",
        "LLM redaction → LLM summarization",
        "Playground for both stages",
        "OCR → prosody"],
     a:0, d:3,
     x:"Compliance-critical redaction uses the deterministic API; the flexible LLM then works on safe text."},
    {q:"Why do identical LLM analysis calls sometimes return different entity lists, and which property of Azure Language fixes it?",
     o:["LLM generation is probabilistic; Azure Language is deterministic — same input, same output",
        "Network jitter changes text",
        "JSON reorders letters",
        "Keys mutate responses"],
     a:0, d:3,
     x:"Probabilistic sampling explains LLM variance; determinism is the documented Azure Language strength."},
    {q:"Which sequence of the speech-synthesis pipeline explains why '2:30pm w/ Dr. Lee' is spoken naturally?",
     o:["Normalization expands abbreviations/numbers → linguistic model maps to phonemes → prosody adds natural cadence → waveform encodes audio",
        "Waveform first, then normalization",
        "Prosody expands the abbreviations",
        "Phonemes are skipped for numbers"],
     a:0, d:3,
     x:"Normalization ('two thirty P M with doctor Lee') precedes phoneme mapping, prosody, and waveform encoding."},
    {q:"A voice agent must handle users interrupting mid-sentence in noisy cafés while calling tools to book tables. Which Foundry capability set matches?",
     o:["Voice Live — real-time speech + generative model with instructions/tools, interruption handling, noise reduction",
        "Batch transcription",
        "The image playground",
        "Content Understanding analyzers"],
     a:0, d:3,
     x:"Continuous, interruptible, tool-using voice conversation is exactly Voice Live."},
    {q:"In STT code, SpeechRecognizer(speech_config=sc, audio_config=ac) — what do sc and ac respectively supply?",
     o:["sc: service key/endpoint configuration; ac: the audio source (file or microphone)",
        "sc: the voice name; ac: the temperature",
        "sc: the transcript; ac: the language",
        "sc: billing; ac: encryption"],
     a:0, d:3,
     x:"SpeechConfig carries connection settings; AudioConfig selects the input source."},
    {q:"A wildlife camera system must (1) decide if any animal is present, then (2) outline each animal's exact shape for research. Choose the task pair:",
     o:["Classification, then semantic segmentation",
        "Segmentation, then classification",
        "Detection, then captioning",
        "Captioning, then OCR"],
     a:0, d:3,
     x:"Whole-image presence check = classification; exact shapes = pixel-level segmentation."},
    {q:"How does a diffusion model generate a fresh image at inference time?",
     o:["It starts from random pixels and iteratively removes learned noise guided by the prompt",
        "It averages all training images",
        "It searches the web for a match",
        "It reverses a CNN's filters"],
     a:0, d:3,
     x:"Generation reverses the noise-adding training process, denoising toward the description."},
    {q:"Why must a client POLL for sora video-generation results?",
     o:["Video generation is resource-intensive and long-running, so it is exposed as an asynchronous job",
        "HTTP cannot carry video",
        "Polling reduces cost to zero",
        "sora only works at night"],
     a:0, d:3,
     x:"Async submit-and-poll is the documented pattern for heavy video workloads."},
    {q:"Which line correctly supplies a local photo to a multimodal model?",
     o:["{'type':'input_image','image_url':'data:image/png;base64,' + encoded}",
        "{'type':'photo','bytes':rawBinary}",
        "{'type':'input_image','path':'C:/pics/photo.png'}",
        "{'type':'image','ftp':'ftp://pics/photo.png'}"],
     a:0, d:3,
     x:"Local images are base64-encoded into a data URI (or hosted and passed as a URL)."},
    {q:"OCR reads a form perfectly, yet the expense system receives 'Aug 15 2024' in one record and '2024-08-15' in another. Which pipeline stage is missing?",
     o:["Data normalization and standardization","Text region detection","Audio capture","Attention"],
     a:0, d:3,
     x:"Normalization standardizes extracted values into consistent formats."},
    {q:"A team needs invoice fields extracted with per-field confidence and a defined schema, exposed as JSON. Which service and artifact?",
     o:["Azure Content Understanding with an invoice analyzer",
        "Azure Speech with Voice Live",
        "The model catalog's leaderboard",
        "A resource lock"],
     a:0, d:3,
     x:"Content Understanding analyzers return schema-mapped fields with confidence, via the REST API as JSON."},
    {q:"Match the tool need: an agent must (1) search uploaded policy files and (2) create calendar events. Which agent tool categories?",
     o:["(1) knowledge tool; (2) action tool",
        "(1) action tool; (2) knowledge tool",
        "Both are models",
        "Both are guardrails"],
     a:0, d:3,
     x:"Knowledge tools retrieve grounding information; action tools change external state."},
    {q:"Which claim about Foundry and Azure infrastructure is FALSE?",
     o:["Foundry can operate with no Azure subscription",
        "Foundry uses Azure identity and security",
        "Foundry resources provide compute and model delivery",
        "Foundry projects live inside Foundry resources"],
     a:0, d:3,
     x:"Foundry is built on Azure — a subscription and its resources are required."},
    {q:"An exam scenario requires the SAME summary sentence count from every article and traceable sentence origins. Which summarization style fits?",
     o:["Extractive summarization (e.g., TextRank) selecting the top-n sentences",
        "Freeform LLM abstractive summarization",
        "Speech diarization",
        "Bag-of-Words"],
     a:0, d:3,
     x:"Extractive methods pick n existing sentences — countable and traceable; abstractive output varies."},
    {q:"Which design keeps a customer-facing model from discussing competitors, regardless of user prompts?",
     o:["Behavior rules in the system instructions plus deployment guardrails",
        "Higher temperature",
        "A bigger context window",
        "Renaming the deployment"],
     a:0, d:3,
     x:"Scope restrictions belong in instructions; guardrails add policy-level enforcement."},
    {q:"A model deployment auto-updated overnight and outputs changed. Which deployment consideration would have prevented surprise, and how?",
     o:["Version — pinning the model version / controlling the auto-update policy",
        "Rate limits — throttling updates",
        "Guardrails — blocking versions",
        "Deployment type — changing region"],
     a:0, d:3,
     x:"The version setting governs which model version runs and whether it auto-updates."},
    {q:"Which statement about MCP (Model Context Protocol) in Foundry is TRUE?",
     o:["MCP servers expose service capabilities (like Azure Language or Speech) to agents as callable tools",
        "MCP replaces the agent's model",
        "MCP is a video codec",
        "MCP is only for image generation"],
     a:0, d:3,
     x:"MCP is the tool-integration protocol connecting agents to Foundry Tools services."},
    {q:"A proof-of-concept works via the playground. To ship it, the team must move to code. Which minimal Python stack applies for a chat feature?",
     o:["openai package + endpoint + API key/token + deployment name",
        "kubernetes + helm + docker",
        "pandas + matplotlib",
        "azure.storage.blob only"],
     a:0, d:3,
     x:"The OpenAI-compatible SDK against the Foundry endpoint with credentials and the deployment name is the minimal path."}
  ]
};
