window.BANKS = window.BANKS || {};
window.BANKS.final2 = {
  title: "Final Mock Exam 2 — AI-901 (full syllabus)",
  minutes: 60,
  questions: [
    // ===== EASY (11) =====
    {q:"Which list contains ONLY common AI workloads?",
     o:["Generative AI & agents, text & language, speech, vision, information extraction",
        "DNS, DHCP, TCP/IP, HTTP",
        "Backup, patching, monitoring",
        "Spreadsheets, word processing, e-mail"],
     a:0, d:1,
     x:"The five workloads: generative AI & agents, text & language, computer speech, computer vision, information extraction."},
    {q:"Users and services in an Azure tenant are authenticated by:",
     o:["Microsoft Entra ID","Azure CDN","Azure Files","Windows Update"],
     a:0, d:1,
     x:"Microsoft Entra ID is the identity service at the tenant level."},
    {q:"An agent's 'instructions' define its:",
     o:["Behavior and scope","GPU allocation","Billing account","IP address"],
     a:0, d:1,
     x:"Instructions are the agent's job description — behavior, scope, and tone."},
    {q:"Which responsible AI principle says AI should empower everyone, including people with disabilities?",
     o:["Inclusiveness","Fairness","Accountability","Reliability & safety"],
     a:0, d:1,
     x:"Inclusiveness covers benefiting all people, expressly including those with disabilities."},
    {q:"Vector representations of tokens that capture semantic meaning are called:",
     o:["Embeddings","Checksums","Indexes","Cookies"],
     a:0, d:1,
     x:"Embeddings are the semantic vectors at the heart of language models."},
    {q:"Sentiment analysis is a form of:",
     o:["Text classification","Speech synthesis","Object detection","Field mapping"],
     a:0, d:1,
     x:"Sentiment analysis classifies text by tone — a text-classification task."},
    {q:"The smallest unit of sound in speech is a:",
     o:["Phoneme","Pixel","Token","Byte"],
     a:0, d:1,
     x:"Phonemes are the smallest units of sound — the currency of acoustic and linguistic modeling."},
    {q:"Which model type generates images from random noise guided by a text description?",
     o:["Diffusion model","Decision tree","Naïve Bayes","TF-IDF"],
     a:0, d:1,
     x:"Diffusion models denoise random pixels toward the prompt."},
    {q:"A model that accepts text AND images in the same prompt is:",
     o:["Multimodal","Multithreaded","Multitenant","Multicast"],
     a:0, d:1,
     x:"Multimodal models work with more than one data type."},
    {q:"Content Understanding analyzers come in which two kinds?",
     o:["Predefined and custom","Public and private","Fast and slow","Local and remote"],
     a:0, d:1,
     x:"Predefined analyzers cover common documents; custom analyzers use your own schema from samples."},
    {q:"Which portal surface lets you interactively chat with a deployed model?",
     o:["The model playground","The billing blade","Azure DNS zones","The activity log"],
     a:0, d:1,
     x:"The playground is the interactive test surface for deployed models (and agents)."},
    // ===== MODERATE (11) =====
    {q:"A council must show residents which factors its benefits-eligibility AI considers. Which principle is served?",
     o:["Transparency","Reliability & safety","Privacy & security","Fairness"],
     a:0, d:2,
     x:"Explaining what the system considers and how it behaves is transparency."},
    {q:"Which model-catalog capability directly helps you pick between two summarization models?",
     o:["Comparing models side by side in the catalog",
        "Deleting one of them",
        "Renaming deployments",
        "Changing the resource group"],
     a:0, d:2,
     x:"The catalog supports discovering, filtering, and comparing models across providers."},
    {q:"What is the role of a system prompt (instructions)?",
     o:["To specify context and guidelines for how the model responds",
        "To store the API key",
        "To set the rate limit",
        "To choose the Azure region"],
     a:0, d:2,
     x:"Instructions guide response behavior — tone, scope, format, refusals."},
    {q:"Stop-word removal, stemming, and POS tagging all belong to:",
     o:["Text pre-processing","Speech synthesis","Image generation","Field normalization"],
     a:0, d:2,
     x:"These steps prepare raw text for statistical or semantic analysis."},
    {q:"client.recognize_pii_entities(docs) returns which trio?",
     o:["Redacted text, entity list with categories, confidence per entity",
        "A translation, a summary, a poem",
        "Language name, ISO code, confidence",
        "Bounding boxes, masks, captions"],
     a:0, d:2,
     x:"PII detection yields redaction plus categorized entities with confidence scores."},
    {q:"Which pipeline stage of speech recognition produces the FINAL formatted transcript?",
     o:["Post-processing","Audio capture","Acoustic modeling","Feature extraction"],
     a:0, d:2,
     x:"Post-processing normalizes and formats the recognized word sequence into clean text."},
    {q:"Which is the correct high-level flow for an app calling a Foundry model with the OpenAI library?",
     o:["Create client (endpoint+key) → responses.create(model=deployment, input=prompt) → read output",
        "Upload weights → compile → run locally",
        "Open a socket → send raw text → parse HTML",
        "Email the prompt → await reply"],
     a:0, d:2,
     x:"Client construction then responses.create is the standard consumption pattern."},
    {q:"A CNN's final output layer for classification provides:",
     o:["A probability for each class","A pixel mask","A text caption","An audio clip"],
     a:0, d:2,
     x:"Classification networks output per-class probabilities."},
    {q:"Which use case belongs to information extraction rather than NLP text analysis?",
     o:["Turning scanned purchase orders into structured records",
        "Scoring tweet sentiment",
        "Detecting the language of an email",
        "Extracting key phrases from typed notes"],
     a:0, d:2,
     x:"Unstructured scanned documents → structured fields is information extraction; the others analyze born-digital text."},
    {q:"Foundry agents gain access to Azure Language capabilities through:",
     o:["The Azure Language MCP server connected as a tool",
        "A CSV import",
        "The billing API",
        "Editing the model weights"],
     a:0, d:2,
     x:"The MCP server exposes Language functions to agents as tools, with approval options."},
    {q:"Why are Fundamentals-level Microsoft certifications attractive for students?",
     o:["They validate skills and do not expire",
        "They require ten years' experience",
        "They replace university degrees",
        "They grant Azure for free forever"],
     a:0, d:2,
     x:"Microsoft fundamentals certifications don't expire and provide industry-recognized validation."},
    // ===== HARD (23) =====
    {q:"A triage model for loan APPROVALS also logs who overrode each AI decision and why. Which TWO principles does the logging support?",
     o:["Accountability and transparency",
        "Fairness and inclusiveness",
        "Privacy and reliability",
        "Inclusiveness and privacy"],
     a:0, d:3,
     x:"Override logs keep humans answerable (accountability) and make system behavior traceable/understandable (transparency)."},
    {q:"Which architecture statement is TRUE of both LLMs and Vision Transformers?",
     o:["Both use attention over embedded units (tokens or image patches) to encode contextual relationships",
        "Both use convolution filters",
        "Both output audio",
        "Neither can be deployed in Foundry"],
     a:0, d:3,
     x:"ViTs adapt the transformer's attention mechanism from language tokens to image patches."},
    {q:"A dev requests 'always route my requests through the refunds agent' in code. Which API element accomplishes it?",
     o:["extra_body={'agent': {'name': agent.name, 'type': 'agent_reference'}} on responses.create",
        "A higher temperature",
        "A base64 image part",
        "A DNS CNAME"],
     a:0, d:3,
     x:"The agent_reference in extra_body directs the request to the named Foundry agent."},
    {q:"Rank these for making an LLM's answers use YOUR company's leave policy: (best practice first)",
     o:["Attach the policy as agent knowledge (file search) so answers are grounded",
        "Hope the base model memorized your policy",
        "Raise max tokens",
        "Lower the rate limit"],
     a:0, d:3,
     x:"Grounding via knowledge tools is the correct mechanism; base models don't know private policies."},
    {q:"Your text pipeline must classify 100k historic tickets ONCE for a migration, then never again, and leadership wants rich natural-language rationales per ticket. Which trade-off decision is defensible?",
     o:["A general-purpose model — flexibility and rationale text matter more than run-to-run determinism for a one-off job",
        "Azure Language only — rationales are forbidden",
        "Neither can classify text",
        "Manual review of all 100k"],
     a:0, d:3,
     x:"For a one-time, explanation-rich task, LLM flexibility fits; determinism matters for repeated pipelines."},
    {q:"Why does TF-IDF assign a LOW score to the word 'the' in every document?",
     o:["Its document frequency across the corpus is maximal, so the inverse-document-frequency factor approaches zero",
        "It is too short to count",
        "Stop words are encrypted",
        "TF ignores articles"],
     a:0, d:3,
     x:"Words appearing in virtually all documents get near-zero IDF, wiping out their weight."},
    {q:"A meeting-transcription feature must label WHO spoke each sentence. Which capability must be enabled?",
     o:["Speaker diarization","Language identification","Prosody generation","Guardrails"],
     a:0, d:3,
     x:"Diarization attributes transcript segments to distinct speakers."},
    {q:"In TTS, which stage failure produces 'three-zero-zero-p-m' being read out letter by letter?",
     o:["Normalization failed to expand '3:00pm' into speakable words",
        "Prosody was too natural",
        "The waveform encoder clipped",
        "The acoustic model mapped phonemes wrongly"],
     a:0, d:3,
     x:"Un-normalized numerals/abbreviations reach phoneme mapping in unspeakable form."},
    {q:"An engineer claims: 'The Voice Live SDK stores all call audio permanently in Azure Storage.' Correct them.",
     o:["The SDK opens a real-time connection, streams audio, and handles responses/interruptions — persistence is the app's responsibility",
        "The claim is accurate",
        "Voice Live has no SDK",
        "Storage is mandatory for TTS"],
     a:0, d:3,
     x:"azure-ai-voicelive manages the live session; it does not archive audio."},
    {q:"A farm robot must treat weeds but spare crops, requiring per-pixel plant identification in real time. Which task and typical model?",
     o:["Semantic segmentation, e.g., built on CNN/ViT-based vision models",
        "Whole-image classification with a BoW model",
        "OCR with an invoice analyzer",
        "TTS with neural voices"],
     a:0, d:3,
     x:"Pixel-level discrimination is segmentation, implemented with modern vision architectures."},
    {q:"Which line of reasoning best explains why image URLs and base64 are BOTH supported for multimodal prompts?",
     o:["URLs suit hosted images with small payloads; base64 suits local/private images that must travel inside the request",
        "URLs are for PNG, base64 for JPEG only",
        "Base64 is faster than URLs in all cases",
        "URLs bypass content policies"],
     a:0, d:3,
     x:"The two options cover hosted vs local/private image scenarios."},
    {q:"Your gpt-image deployment returns policy-refusal errors for certain prompt categories. Which mechanism is acting?",
     o:["Guardrails / responsible-AI policies on the deployment",
        "TPM rate limits",
        "The version pin",
        "The resource lock"],
     a:0, d:3,
     x:"Content refusals stem from responsible-AI guardrails, not throughput or versioning settings."},
    {q:"A submitted sora job returns an ID immediately. What does the client hold, and what must it do next?",
     o:["A job reference — poll the job's status endpoint until generation completes, then download the video",
        "The finished MP4 in the ID string",
        "A refund voucher",
        "The model's weights"],
     a:0, d:3,
     x:"Async jobs return a reference; clients poll for completion before retrieving output."},
    {q:"Which OCR-pipeline reasoning is CORRECT?",
     o:["Enhancing the image before region detection improves recognition because cleaner input yields better localization and classification of characters",
        "Recognition happens before acquisition",
        "Region detection outputs the final JSON",
        "Post-processing captures the photo"],
     a:0, d:3,
     x:"Pipeline order matters: early enhancement improves every downstream stage. Acquisition → enhance → detect → recognize → output."},
    {q:"An analyzer schema defines 'PolicyNumber' but incoming letters write it as 'Policy #', 'Pol. No.' and 'Reference'. Why can a semantic analyzer still map these?",
     o:["Generative/semantic models match values to fields by meaning, not exact labels",
        "Regex is built into every PDF",
        "The schema renames the letters",
        "It cannot — mapping requires identical labels"],
     a:0, d:3,
     x:"Semantic field mapping generalizes across label variants — the generative-AI advantage in extraction."},
    {q:"Contrast the OUTPUT of recognize_entities (Azure Language) with an LLM prompted for entities:",
     o:["The SDK returns typed objects with categories and confidence deterministically; the LLM returns free-form text that may vary",
        "Both return identical typed objects",
        "The SDK returns prose; the LLM returns typed objects",
        "Neither returns entities"],
     a:0, d:3,
     x:"Structured determinism vs flexible prose is the core contrast the exam tests."},
    {q:"Your Foundry project has one deployed model shared by a chatbot and a batch summarizer. The batch job starves the chatbot at month-end. Which lever addresses this?",
     o:["Rate limits / separate deployments to allocate tokens-per-minute appropriately",
        "System prompt changes",
        "Bigger guardrails",
        "A new tenant"],
     a:0, d:3,
     x:"Throughput contention is managed via TPM rate limits and deployment separation."},
    {q:"Which claim about agents versus plain model calls is FALSE?",
     o:["Agents cannot use more than one tool",
        "Agents pair a model with instructions and tools",
        "Plain model calls suit simple one-shot completions",
        "Agents can collaborate in multi-agent workflows"],
     a:0, d:3,
     x:"Agents may use multiple tools (knowledge + actions). The other statements are true."},
    {q:"A campus wants ID-card photos matched to names on file for event check-in, plus consent notices displayed. Which pairing of workload and principle applies?",
     o:["Computer vision, with privacy & security (and transparency) obligations",
        "Speech synthesis with fairness",
        "Information extraction with inclusiveness",
        "NLP with reliability"],
     a:0, d:3,
     x:"Face/photo matching is vision; handling biometric data invokes privacy (and consent notices support transparency)."},
    {q:"Which statement about Foundry endpoints and REST is CORRECT?",
     o:["Requests carry function details, headers, and JSON data; responses return headers and JSON results",
        "Requests use XML; responses use CSV",
        "Endpoints only accept binary protobuf",
        "Responses omit headers entirely"],
     a:0, d:3,
     x:"Foundry endpoints expose REST interfaces exchanging JSON payloads with metadata headers."},
    {q:"An intern's script calls the Language SDK once per sentence in a 10,000-sentence corpus and hits throttling. Which improvement matches the SDK's design?",
     o:["Submit documents in batches — the API accepts a collection of documents per call",
        "Add a GPU",
        "Switch to XML",
        "Call the playground instead"],
     a:0, d:3,
     x:"The SDK methods take document collections; batching reduces calls and throttling."},
    {q:"To let faculty grade consistently, a mock-exam generator must ALWAYS produce the same difficulty distribution. Which design choice mirrors the deterministic-vs-probabilistic lesson?",
     o:["Author a fixed question bank with tagged difficulties, rather than generating questions live with an LLM per student",
        "Generate fresh questions per student at temperature 1.0",
        "Let each student pick their difficulty",
        "Randomize the pass mark"],
     a:0, d:3,
     x:"Fixed, tagged banks give reproducible distributions; live LLM generation varies run to run — the same trade-off as text analysis routes."},
    {q:"Final synthesis: a startup will (1) chat over docs, (2) transcribe calls, (3) extract invoice fields, (4) generate product images. Map each to Foundry capabilities:",
     o:["(1) agent with knowledge tools; (2) Azure Speech STT; (3) Content Understanding analyzer; (4) text-to-image model deployment",
        "(1) sora; (2) gpt-image; (3) Voice Live; (4) TextAnalytics",
        "(1) OCR; (2) diffusion; (3) TTS; (4) NER",
        "(1) guardrails; (2) rate limits; (3) versions; (4) deployment types"],
     a:0, d:3,
     x:"Doc chat = agent + knowledge; transcription = Speech; invoice fields = Content Understanding; image generation = text-to-image models."}
  ]
};
