window.BANKS = window.BANKS || {};
window.BANKS.q1a = {
  title: "Quiz 1A — AI Concepts & Getting Started with AI in Azure",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Which statement best describes artificial intelligence?",
     o:["Software that imitates human capabilities such as prediction, decision-making, and language understanding",
        "Any program that stores large amounts of data in the cloud",
        "Hardware designed to run spreadsheets faster",
        "A database technology for structured records"],
     a:0, d:1,
     x:"AI is software that imitates human capabilities — predicting outcomes, evaluating content and making decisions, understanding language, interpreting visual input, and extracting information."},
    {q:"Which technology underpins every AI workload, conceptually expressed as f(x) = y?",
     o:["Blockchain","Machine learning","Virtualization","Edge computing"],
     a:1, d:1,
     x:"Machine learning — models trained on historic data that map an input (x) to an output (y) — is the foundation on which all AI workloads are built."},
    {q:"An application that can perform tasks on behalf of a user is called:",
     o:["A data pipeline","A REST API","An AI agent","A virtual machine"],
     a:2, d:1,
     x:"An AI agent is an AI application that performs tasks on behalf of a user — it is software, not a person who builds or uses AI."},
    {q:"In Azure, which construct defines the organizational security boundary?",
     o:["Resource group","Subscription","Tenant","Region"],
     a:2, d:1,
     x:"The tenant is the security boundary of an organization; users and services in it are identified and authenticated using Microsoft Entra ID."},
    {q:"Which Azure construct provides the billing boundary?",
     o:["Tenant","Subscription","Resource group","Management certificate"],
     a:1, d:1,
     x:"Within a tenant, subscriptions define billing boundaries. Resource groups exist for organization and management, not billing."},
    {q:"Which service authenticates users and services within an Azure tenant?",
     o:["Azure DNS","Microsoft Entra ID","Azure Monitor","Azure Key Vault"],
     a:1, d:1,
     x:"Microsoft Entra ID is Azure's identity service — it identifies and authenticates users and services within a tenant."},
    {q:"What is Microsoft Foundry?",
     o:["A version-control system for AI code",
        "A unified Azure platform for building AI apps and agents",
        "A Windows desktop application for editing images",
        "A subscription tier of Microsoft 365"],
     a:1, d:1,
     x:"Microsoft Foundry is a unified platform — a comprehensive set of Azure services — for building AI apps and agents."},
    {q:"In a Foundry project, which asset type is used to choose and deploy AI models from a catalog?",
     o:["Knowledge","Tools","Models","Agents"],
     a:2, d:1,
     x:"The Models asset lets you browse the extensive model catalog and deploy models. Agents use models; tools and knowledge extend agents."},
    // ---- MODERATE (7) ----
    {q:"A company publishes documentation explaining what data its AI hiring system uses and how it reaches decisions. Which responsible AI principle is being applied?",
     o:["Inclusiveness","Transparency","Reliability & safety","Privacy & security"],
     a:1, d:2,
     x:"Transparency means making an AI system's purpose, behavior, and limitations understandable to the people who use it."},
    {q:"A medical-prediction model must be rigorously tested to confirm it operates correctly under all expected conditions before release. Which principle does this address?",
     o:["Fairness","Accountability","Reliability & safety","Transparency"],
     a:2, d:2,
     x:"Reliability & safety requires AI systems to perform dependably within defined operational limits and to be tested rigorously."},
    {q:"Which sequence correctly orders Azure constructs from outermost to innermost?",
     o:["Subscription → Tenant → Resource → Resource group",
        "Tenant → Subscription → Resource group → Resource",
        "Resource group → Subscription → Tenant → Resource",
        "Tenant → Resource group → Subscription → Resource"],
     a:1, d:2,
     x:"A tenant (security boundary) contains subscriptions (billing boundaries), which contain resource groups, which contain resources."},
    {q:"What is the role of a Foundry project?",
     o:["It replaces the Azure subscription for billing purposes",
        "It provides an isolated work environment for app and agent development",
        "It stores API keys for all Azure services in the tenant",
        "It hosts the physical GPUs used by models"],
     a:1, d:2,
     x:"Foundry projects are isolated work environments where you develop apps and agents, working with models, agents, tools, and knowledge."},
    {q:"Which TWO items together let an application call a deployed Foundry model? (choose the single option that lists both)",
     o:["A storage account and a virtual network",
        "An endpoint URL and an API key (or Entra ID token)",
        "A resource group and a subscription ID",
        "A model version number and a region name"],
     a:1, d:2,
     x:"Applications call the endpoint (an HTTPS address) and authenticate with an API key or a Microsoft Entra ID token."},
    {q:"What data format do Foundry endpoint requests and responses use in their bodies?",
     o:["XML","CSV","JSON","YAML"],
     a:2, d:2,
     x:"Requests carry function details and data as JSON, and responses return operation results as JSON, along with metadata headers."},
    {q:"Why do developers typically use SDKs rather than calling Foundry REST APIs directly?",
     o:["SDKs bypass authentication requirements",
        "SDKs abstract the REST APIs into language-specific libraries that are easier to code against",
        "REST APIs are deprecated in Azure",
        "SDKs run models locally without an endpoint"],
     a:1, d:2,
     x:"REST APIs are typically abstracted by language-specific SDKs (Python, C#, …) that simplify coding. Auth is still required and models still run in the cloud."},
    // ---- HARD (15) ----
    {q:"A bank discovers its loan-approval model recommends rejections far more often for one postal region with a specific demographic profile, despite similar financial data. Which responsible AI principle is MOST directly violated?",
     o:["Transparency","Fairness","Inclusiveness","Accountability"],
     a:1, d:3,
     x:"Fairness requires AI to treat all people equitably and avoid bias linked to demographic characteristics. Transparency concerns explainability, not equitable outcomes."},
    {q:"A voice assistant is updated so users who are deaf can receive the same information through real-time captions. Which principle does this BEST demonstrate?",
     o:["Inclusiveness","Reliability & safety","Fairness","Privacy & security"],
     a:0, d:3,
     x:"Inclusiveness means AI should empower everyone, including people with disabilities. Fairness is about equitable treatment across groups in decisions, which is different from designing for accessibility."},
    {q:"An AI vendor establishes a governance board with authority to override the system's automated decisions and answer for its outcomes. Which principle is applied?",
     o:["Transparency","Reliability & safety","Accountability","Fairness"],
     a:2, d:3,
     x:"Accountability keeps humans answerable for AI systems — governance structures and human override authority are its hallmark."},
    {q:"A company trains a model using customer purchase histories. To comply with responsible AI, personal details must be protected both during training AND when the deployed model handles requests. Which principle covers this end-to-end obligation?",
     o:["Privacy & security","Transparency","Inclusiveness","Reliability & safety"],
     a:0, d:3,
     x:"Privacy & security applies to the data used for training and to data processed at inference time — protection must span the whole lifecycle."},
    {q:"Which statement about the relationship between Microsoft Foundry and Azure is accurate?",
     o:["Foundry replaces Azure services entirely as a standalone AI cloud",
        "Foundry runs independently and needs no Azure resources",
        "Foundry is built on Azure and relies on Azure compute, networking, identity, and security",
        "Foundry is an on-premises product that synchronizes with Azure"],
     a:2, d:3,
     x:"Foundry is built on top of Azure and uses Azure resources — compute, networking, identity, security — to host and operate AI applications."},
    {q:"A developer says: 'The endpoint stores our secrets, and the key controls how much data the endpoint may return.' What is wrong with this statement?",
     o:["Nothing — it is accurate",
        "Endpoints are URLs for calling deployed models, and keys authenticate requests; neither stores secrets nor limits data volume",
        "Keys actually store the model responses",
        "Endpoints authenticate requests while keys address the model"],
     a:1, d:3,
     x:"The endpoint is simply the HTTPS address of the deployed model; the key (or Entra ID token) proves the caller is authorized. Secrets storage is a different concern (e.g., Key Vault)."},
    {q:"Your team needs separate development and production AI workspaces whose costs must appear on different invoices. At which Azure level should the environments be separated?",
     o:["Two resource groups in one subscription","Two subscriptions","Two regions in one resource group","Two tenants sharing one subscription"],
     a:1, d:3,
     x:"Subscriptions are the billing boundary — separate invoices require separate subscriptions. Resource groups organize resources but share their subscription's bill."},
    {q:"Within a Foundry project, an agent must look up company policy documents before answering staff questions. Which project asset type manages the agent's access to those data sources?",
     o:["Models","Knowledge","Tools (actions)","Deployments"],
     a:1, d:3,
     x:"Knowledge manages data-source access for agents so they have the information they need. Actions automate tasks; models provide reasoning."},
    {q:"Which capability list belongs to AI as defined in this course?",
     o:["Predicting outcomes, interpreting visual input, extracting information from sources",
        "Compiling source code, defragmenting disks, routing network packets",
        "Rendering 3D graphics, mining cryptocurrency, compressing files",
        "Hosting websites, load balancing, DNS resolution"],
     a:0, d:3,
     x:"AI imitates human capabilities: prediction and pattern recognition, decision-making, language understanding, visual interpretation, and information extraction."},
    {q:"A request to a Foundry endpoint fails with an authentication error even though the URL is correct. Which is the MOST likely cause?",
     o:["The JSON body used lowercase field names",
        "The API key or Entra ID token supplied is missing or invalid",
        "The resource group is in a different region",
        "The response format was set to JSON"],
     a:1, d:3,
     x:"Connections to endpoints are authenticated by an authorization key or Microsoft Entra ID token — an auth failure points to the credential, not to JSON formatting or resource-group location."},
    {q:"Which pairing of AI workload to scenario is INCORRECT?",
     o:["Computer vision — detecting helmets in factory CCTV footage",
        "Information extraction — pulling totals from scanned invoices",
        "Computer speech — summarizing a legal contract PDF",
        "Text & language — classifying support tickets by sentiment"],
     a:2, d:3,
     x:"Summarizing a contract PDF is a text/language (or information-extraction) task. Computer speech deals with spoken audio — recognition and synthesis."},
    {q:"A solution generates original marketing copy from short text briefs and can also draft images for the campaign. Which workload is this?",
     o:["Information extraction","Generative AI","Computer vision","Machine-learning regression"],
     a:1, d:3,
     x:"Generative AI creates original content — text, images, code — in response to natural-language prompts."},
    {q:"Your Foundry-based chatbot needs to both search the web for fresh information and file support tickets automatically. In agent terms, these two capabilities are examples of:",
     o:["Models and endpoints","Knowledge and actions provided through tools","Subscriptions and resource groups","Instructions and parameters"],
     a:1, d:3,
     x:"Agents use tools for two purposes: finding knowledge to contextualize their work (web/file search) and performing actions to automate tasks (filing tickets)."},
    {q:"Which statement about Foundry resources vs Foundry projects is TRUE?",
     o:["Projects provide compute and storage; resources are isolated dev environments",
        "Resources provide compute, storage, and model delivery; projects are isolated environments inside them",
        "Resources and projects are interchangeable names for the same object",
        "A project can exist without any Foundry resource"],
     a:1, d:3,
     x:"The Foundry resource supplies the underlying services (compute, storage, model delivery); projects are the isolated work environments created within it."},
    {q:"A university lab wants students to experiment with AI without affecting the faculty's production resources, while all costs stay on the university's single invoice. What is the BEST structure?",
     o:["Separate tenants for each student",
        "One subscription with separate resource groups for student and production workloads",
        "One resource group containing everything",
        "Separate subscriptions for every student"],
     a:1, d:3,
     x:"Resource groups organize and manage resources independently within one subscription (one bill). Separate tenants/subscriptions would split billing and identity unnecessarily."}
  ]
};
