window.BANKS = window.BANKS || {};
window.BANKS.q1b = {
  title: "Quiz 1B — AI Concepts & Getting Started with AI in Azure (round 2)",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"How many principles make up Microsoft's responsible AI framework?",
     o:["Four","Five","Six","Eight"],
     a:2, d:1,
     x:"Six principles: fairness, reliability & safety, privacy & security, inclusiveness, transparency, and accountability."},
    {q:"Which AI workload converts documents, receipts, audio, and video into structured, usable data?",
     o:["Computer speech","Information extraction","Generative AI","Text classification"],
     a:1, d:1,
     x:"Information extraction analyzes unstructured content (documents, forms, images, audio, video) and extracts relevant fields and values."},
    {q:"An HTTPS address that applications use to access a deployed model or Foundry service is called:",
     o:["A resource lock","An endpoint","A service principal","A namespace"],
     a:1, d:1,
     x:"An endpoint is the HTTP(S) address through which applications access Foundry assets such as deployed models."},
    {q:"Which of the following is one of the four asset types you work with in a Foundry project?",
     o:["Firewalls","Agents","Containers","Pipelines"],
     a:1, d:1,
     x:"Foundry projects contain models, agents, tools, and knowledge."},
    {q:"Which responsible AI principle focuses on protecting the data used to train and operate AI systems?",
     o:["Privacy & security","Fairness","Transparency","Inclusiveness"],
     a:0, d:1,
     x:"Privacy & security requires safeguarding the data an AI system is trained on and the data it processes when running."},
    {q:"What kind of boundary does a resource group provide?",
     o:["Billing boundary","Security/identity boundary","Organization and management grouping","Network isolation boundary"],
     a:2, d:1,
     x:"Resource groups exist to organize and manage related resources. Billing is the subscription; security/identity is the tenant."},
    {q:"Which of these is an example of generative AI output?",
     o:["A sorted database table","An original poem written from a prompt","A compressed ZIP archive","A disk-usage report"],
     a:1, d:1,
     x:"Generative AI creates original content — text, images, code — in response to prompts."},
    {q:"Interpreting the content of images and video belongs to which workload?",
     o:["Computer vision","Information extraction","Computer speech","Text & language"],
     a:0, d:1,
     x:"Computer vision is the workload concerned with interpreting visual input such as images and video."},
    // ---- MODERATE (7) ----
    {q:"Which HTTP elements accompany the JSON body in a Foundry endpoint request?",
     o:["Binary attachments only","Metadata headers","XML envelopes","Cookies signed by the model"],
     a:1, d:2,
     x:"Requests include the function details and data as JSON plus metadata headers; responses likewise return headers and JSON results."},
    {q:"A city deploys an AI traffic system and assigns a named officer with authority to review and reverse its decisions. Which principle is this?",
     o:["Accountability","Transparency","Reliability & safety","Fairness"],
     a:0, d:2,
     x:"Accountability keeps people answerable for AI systems — designated humans who can review and override decisions."},
    {q:"What is the correct description of the Foundry model catalog's scope?",
     o:["Only Microsoft-built models","Models from Microsoft plus partner and community providers","Only open-source models","Only speech models"],
     a:1, d:2,
     x:"The catalog includes models sold directly by Microsoft (billed via Azure) and models from partner/community providers."},
    {q:"Your app authenticates to a Foundry endpoint without storing any secret in code, using the identity assigned to the app. Which mechanism is this?",
     o:["An API key embedded in HTML","A Microsoft Entra ID token","A shared CSV of passwords","An anonymous connection"],
     a:1, d:2,
     x:"Endpoint connections can be authenticated by an authorization key or by a Microsoft Entra ID token — token-based auth avoids embedding secrets."},
    {q:"Which scenario is text & language (NLP) rather than information extraction?",
     o:["Reading vendor and total from scanned receipts",
        "Determining that incoming product reviews are mostly negative",
        "Pulling invoice numbers from PDF files into a database",
        "Transcribing a recorded phone call"],
     a:1, d:2,
     x:"Sentiment analysis of reviews is a classic NLP text-classification task. Receipt/invoice field extraction is information extraction; call transcription is speech."},
    {q:"Which statement about machine learning's relationship to AI workloads is correct?",
     o:["Only computer vision uses machine learning",
        "Machine learning is a legacy approach replaced by generative AI",
        "Machine learning models underpin all the AI workloads, including generative AI",
        "Machine learning applies only to numeric data"],
     a:2, d:2,
     x:"Every workload — language, speech, vision, extraction, generative AI — is built on machine-learned models that map inputs to outputs."},
    {q:"Where do agents get the ability to perform actions such as booking a meeting?",
     o:["From larger context windows","From tools connected to the agent","From higher rate limits","From the resource group configuration"],
     a:1, d:2,
     x:"Tools connect agents to capabilities: knowledge tools supply information, action tools let the agent automate tasks."},
    // ---- HARD (15) ----
    {q:"A recruitment AI is found to score candidates from one university systematically higher because historic hiring data favored them. The vendor fixes the training data. Which principle drove the fix?",
     o:["Fairness","Transparency","Privacy & security","Reliability & safety"],
     a:0, d:3,
     x:"Bias inherited from unrepresentative historic data is a fairness problem — AI must treat all people equitably."},
    {q:"An autonomous forklift is certified only for dry indoor floors, and the manufacturer blocks operation when moisture sensors trigger. Which principle is being enforced?",
     o:["Inclusiveness","Reliability & safety","Accountability","Fairness"],
     a:1, d:3,
     x:"Reliability & safety means systems operate only within the limits they were designed and tested for — refusing unsafe conditions enforces this."},
    {q:"A public-sector chatbot displays a notice describing what it can and cannot answer and warns users that responses may contain mistakes. Which TWO principles does the notice serve? (pick the option naming both)",
     o:["Transparency and accountability","Fairness and inclusiveness","Privacy & security and reliability","Inclusiveness and accountability"],
     a:0, d:3,
     x:"Explaining capabilities/limits is transparency; publicly owning responsibility for the system's behavior supports accountability."},
    {q:"Which statement about tenants and subscriptions is FALSE?",
     o:["A tenant can contain multiple subscriptions",
        "Users are authenticated at the tenant level via Microsoft Entra ID",
        "A subscription defines the security boundary of an organization",
        "Resource groups live inside subscriptions"],
     a:2, d:3,
     x:"The tenant, not the subscription, is the security boundary. Subscriptions are billing boundaries within a tenant."},
    {q:"A developer creates a Foundry project and wants an app to call its deployed model. Which minimal information must the app be given?",
     o:["Tenant ID and region","Project endpoint plus a key or token, and the model deployment name","Resource group name and subscription ID","The model's training-data location"],
     a:1, d:3,
     x:"Client code targets the endpoint, authenticates with a key or Entra ID token, and names the model deployment it wants to invoke."},
    {q:"Why might an organization choose Entra ID tokens over API keys for production endpoint access?",
     o:["Tokens make responses faster",
        "Identity-based access removes shared static secrets and supports centralized control",
        "Keys only work in the playground",
        "Tokens are required for JSON responses"],
     a:1, d:3,
     x:"Entra ID authentication ties access to managed identities — no shared static secret to leak or rotate manually. Both methods are otherwise functionally supported."},
    {q:"An insurer's claims triage bot must decide payouts. Regulators demand that a human can always be identified as responsible for each decision. Which principle does the requirement target, and which supporting practice fits?",
     o:["Accountability — human review workflow with named owners",
        "Transparency — publishing the model architecture",
        "Fairness — rebalancing training data",
        "Privacy — encrypting the claims database"],
     a:0, d:3,
     x:"Naming responsible humans and adding review workflows is the accountability principle in action."},
    {q:"Which is the BEST example of the 'evaluating content, making decisions, and taking action' capability of AI?",
     o:["A model that flags fraudulent transactions and automatically holds them for review",
        "A script that renames files by date",
        "A dashboard that charts last month's sales",
        "A backup job that runs nightly"],
     a:0, d:3,
     x:"Evaluating input (transactions), deciding (fraud or not), and acting (holding the payment) is decision-making AI. The others are conventional automation or reporting."},
    {q:"A Foundry-hosted agent must consult the company's HR policy PDFs (stored as project data) AND send emails via a connected service. Map each need to the correct agent concept:",
     o:["PDFs → actions; email → knowledge",
        "PDFs → knowledge; email → actions",
        "PDFs → instructions; email → model",
        "PDFs → model; email → instructions"],
     a:1, d:3,
     x:"Knowledge grounds the agent in data sources (the PDFs); actions let it perform tasks (sending email) through tools."},
    {q:"Which consequence follows from subscriptions being billing boundaries?",
     o:["Resources in different subscriptions cannot communicate",
        "Cost separation between departments is achieved by giving each its own subscription",
        "Each subscription requires its own tenant",
        "Only one resource group may exist per subscription"],
     a:1, d:3,
     x:"Separate subscriptions produce separate billing scopes — the standard way to separate departmental costs. Communication across subscriptions is still possible."},
    {q:"A startup wants to prototype a chatbot today with minimal setup: create a place to work, pick a model, get an endpoint. Which sequence matches the Foundry workflow?",
     o:["Create a Foundry project → deploy a model from the catalog → call the project endpoint from code",
        "Create a virtual machine → install the model → open port 80",
        "Create a storage account → upload weights → email Microsoft for a key",
        "Buy a dedicated GPU cluster → configure Kubernetes → train from scratch"],
     a:0, d:3,
     x:"Foundry's flow: create a project (isolated environment), deploy a catalog model, then connect apps via the endpoint with a key/token."},
    {q:"Which option correctly distinguishes generative AI from 'traditional' predictive ML?",
     o:["Generative AI creates new content from prompts; predictive ML estimates outcomes/labels from features",
        "Generative AI needs no training data; predictive ML does",
        "Predictive ML runs only on-premises; generative AI only in the cloud",
        "Generative AI is rule-based; predictive ML is learned"],
     a:0, d:3,
     x:"Both are machine learning, but generative models produce original content in response to prompts, whereas predictive models output classifications or estimates."},
    {q:"During a demo, a model returns results but the JSON body of the request had to describe 'details of the function' being invoked. Which architectural style does this reflect?",
     o:["SOAP remote procedure calls","REST interfaces exposed by the endpoint","FTP file exchange","WebSocket streaming only"],
     a:1, d:3,
     x:"Foundry endpoints expose REST interfaces: clients send requests with function details, headers, and JSON data, and receive JSON results."},
    {q:"An accessibility review recommends adding descriptive audio to your app's visual dashboards so blind users benefit from the AI insights. Refusing this on cost grounds would MOST directly conflict with:",
     o:["Inclusiveness","Reliability & safety","Privacy & security","Transparency"],
     a:0, d:3,
     x:"Inclusiveness says AI should empower everyone, expressly including people with disabilities."},
    {q:"Which claim about Foundry projects and their assets is FALSE?",
     o:["A project can contain multiple deployed models",
        "Agents in a project can be connected to tools",
        "Knowledge configuration controls the data sources agents can use",
        "Each project must contain exactly one agent"],
     a:3, d:3,
     x:"Projects are flexible workspaces — they may contain zero or many agents, along with models, tools, and knowledge configurations."}
  ]
};
