window.BANKS = window.BANKS || {};
window.BANKS.q2a = {
  title: "Quiz 2A — Generative AI & Agents",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"What is a large language model (LLM)?",
     o:["A type of AI model designed to generate human-like text",
        "A model that processes only images",
        "A database optimized for storing long documents",
        "A compression algorithm for text files"],
     a:0, d:1,
     x:"LLMs are AI models built to understand and generate human-like language; they power generative AI."},
    {q:"Which model architecture do modern LLMs use?",
     o:["Decision tree","Transformer","K-means clustering","Linear regression"],
     a:1, d:1,
     x:"LLMs are based on the transformer architecture, which uses embeddings and attention to model language."},
    {q:"What are embeddings?",
     o:["Vector-based representations of tokens that capture semantic meaning",
        "Extra words a model inserts to improve fluency",
        "Compressed copies of the training data",
        "Rules that filter inappropriate content"],
     a:0, d:1,
     x:"Embeddings encode tokens as vectors; semantically similar tokens have similar vector directions."},
    {q:"What is a 'prompt' in generative AI?",
     o:["The model's internal error log",
        "The natural-language input a user provides to get a response",
        "The GPU that runs the model",
        "The license agreement for the model"],
     a:1, d:1,
     x:"Models generate responses based on natural-language prompts supplied by the user or application."},
    {q:"Small language models (SLMs) are best suited to:",
     o:["Devices and resource-constrained environments",
        "Replacing all cloud models",
        "Only image generation",
        "Training other models"],
     a:0, d:1,
     x:"SLMs are compact models used on devices and in other resource-constrained environments."},
    {q:"Which output type is NOT commonly produced by generative AI?",
     o:["Natural-language text","Images and video","Program code","Physical hardware prototypes"],
     a:3, d:1,
     x:"Generative AI produces digital content — text/speech, images/video, and code — not physical objects."},
    {q:"In Foundry, where can you interactively test a deployed model before writing any code?",
     o:["The model playground","Azure DNS","The billing portal","The resource lock pane"],
     a:0, d:1,
     x:"The model playground lets you explore and test models, try prompts, and adjust settings interactively."},
    {q:"An AI agent combines a model, tools, and which third ingredient that defines its behavior and scope?",
     o:["Instructions","A GPU quota","A storage account","A DNS zone"],
     a:0, d:1,
     x:"Agents use a model (reasoning), instructions (behavior and scope), and tools (knowledge and actions)."},
    // ---- MODERATE (7) ----
    {q:"What does the attention mechanism in a transformer do?",
     o:["Removes irrelevant words from input",
        "Examines the relationships between each token and the tokens around it",
        "Flags offensive language",
        "Chooses which GPU processes the request"],
     a:1, d:2,
     x:"Attention weighs how strongly each token relates to surrounding tokens, letting the model encode context."},
    {q:"Which vector-space fact about embeddings is TRUE?",
     o:["Semantically similar tokens have similar directions in vector space",
        "All vectors have identical values",
        "Vectors store the literal spelling of words",
        "Vector length always equals word length"],
     a:0, d:2,
     x:"Embeddings form a multidimensional space where similar meanings point in similar directions — enabling relationships like dog + young ≈ puppy."},
    {q:"Which model-deployment setting determines where data is processed and how you pay?",
     o:["Guardrails","Deployment type","Version pinning","Content filter level"],
     a:1, d:2,
     x:"Deployment type controls the processing location and payment model. Version controls updates; rate limits control TPM; guardrails apply responsible-AI policies."},
    {q:"Increasing a model's temperature parameter generally makes responses:",
     o:["More deterministic and repetitive","More random and 'creative'","Shorter","Grammatically incorrect"],
     a:1, d:2,
     x:"Temperature controls randomness — higher values yield more varied, creative output; lower values are more predictable."},
    {q:"What is the primary benefit of using the model playground before writing code?",
     o:["It removes the need to deploy a model",
        "You can test prompts, compare models, and capture working settings to reuse in code",
        "It automatically writes the perfect system prompt",
        "It eliminates API authentication"],
     a:1, d:2,
     x:"The playground is for experimentation — testing prompts and settings you can then carry into application code. It doesn't replace deployment or the API."},
    {q:"In the OpenAI Python pattern for Foundry, which two values configure the client object?",
     o:["base_url (endpoint) and api_key","subscription ID and tenant ID","region and SKU","model weights and vocabulary"],
     a:0, d:2,
     x:"OpenAI(base_url=<foundry endpoint>, api_key=<key>) creates the client; the model deployment name is passed per request."},
    {q:"Agents can collaborate with which of the following?",
     o:["Human users only",
        "Other agents only",
        "Both human users and other agents",
        "Neither — agents work in isolation"],
     a:2, d:2,
     x:"Agents assist human users and can also participate in multi-agent workflows where specialized agents cooperate."},
    // ---- HARD (15) ----
    {q:"A support chatbot must always answer in formal English, stay on-topic about billing, and refuse legal advice. Which mechanism implements these requirements?",
     o:["Raising the temperature",
        "Writing them into the instructions (system prompt)",
        "Increasing the rate limit",
        "Choosing a larger resource group"],
     a:1, d:3,
     x:"Instructions/system prompts specify context and guidelines for responses — tone, scope, and refusal rules belong there."},
    {q:"Your model deployment intermittently rejects requests during peak hours with throttling errors. Which deployment setting should you examine FIRST?",
     o:["Guardrails","Rate limits (tokens-per-minute)","Model version","System prompt length"],
     a:1, d:3,
     x:"Rate limits cap maximum TPM throughput; exceeding them causes throttling. Guardrails filter content, they don't throttle."},
    {q:"A compliance team wants inappropriate content blocked at the deployment level regardless of what the application sends. Which setting applies?",
     o:["Guardrails (responsible AI policies)","Deployment type","Temperature","Auto-update policy"],
     a:0, d:3,
     x:"Guardrails attach responsible-AI content policies to the deployment itself, independent of application logic."},
    {q:"In this Foundry Project API snippet, which line actually submits the user's question to the agent?\n\n1: agent = project.agents.get(\"helper\")\n2: oc = project.get_openai_client()\n3: r = oc.responses.create(input=[...], extra_body={\"agent\": {...}})",
     o:["Line 1","Line 2","Line 3","None — a separate submit() call is required"],
     a:2, d:3,
     x:"responses.create() sends the prompt. Line 1 only retrieves the agent definition and line 2 only constructs the client."},
    {q:"Why can two identical prompts to the same LLM return different answers?",
     o:["The endpoint caches corrupt data",
        "Generation is probabilistic — the model samples from a distribution over next tokens",
        "JSON encoding randomizes text",
        "Keys expire between calls"],
     a:1, d:3,
     x:"LLMs generate probabilistically; sampling (influenced by temperature) means outputs can vary between identical calls."},
    {q:"A team wants their agent to cite the company travel policy when answering expense questions. The policy lives in uploaded files. Which tool category should be added to the agent?",
     o:["An action tool for code generation",
        "A knowledge tool such as file search",
        "A larger model deployment",
        "A billing export tool"],
     a:1, d:3,
     x:"Knowledge tools (e.g., file search) ground the agent in data sources so it can contextualize answers."},
    {q:"Which statement about the Foundry model catalog is FALSE?",
     o:["It contains models from multiple providers",
        "Microsoft-sold models are billed through your Azure subscription",
        "You can filter and compare models",
        "Using the catalog removes the need for an Azure subscription"],
     a:3, d:3,
     x:"The catalog is a discovery/compare/deploy hub — you still need an Azure subscription; Microsoft-sold models bill through it."},
    {q:"A prompt asks for 'a fun limerick about databases' and the system prompt says 'You are a formal technical writer; never write humor.' What is the LIKELY behavior and why?",
     o:["Humor is produced — user prompts always win",
        "The model follows the system instructions and declines or answers formally, since instructions define behavior and scope",
        "The endpoint returns an HTTP 500",
        "The model switches providers automatically"],
     a:1, d:3,
     x:"Instructions (system prompts) set the governing context and guidelines; well-behaved models respect them over conflicting user prompts."},
    {q:"Which change is MOST likely to make a vague prompt produce the desired output?",
     o:["Adding explicit details and requirements to the user prompt",
        "Doubling the rate limit",
        "Switching from JSON to XML",
        "Restarting the resource group"],
     a:0, d:3,
     x:"Explicit prompts with sufficient detail produce better output — prompt quality is the main lever for response quality."},
    {q:"An architect proposes: 'Deploy once, then let the auto-update policy move us to new model versions automatically.' Which deployment consideration governs this behavior?",
     o:["Version","Deployment type","Guardrails","Knowledge"],
     a:0, d:3,
     x:"The version setting covers both the model version and its auto-update policy."},
    {q:"Your multi-agent workflow has a 'triage' agent that hands tickets to a 'refunds' agent. What enables this pattern?",
     o:["Agents can collaborate with other agents, each with its own responsibility",
        "Both agents must share one system prompt",
        "Azure only permits one agent per tenant",
        "Refunds require a special GPU"],
     a:0, d:3,
     x:"Agents can form workflows of specialized agents that cooperate — a core agentic-AI capability."},
    {q:"To test an agent interactively — including its tools — before wiring it into an app, you should use:",
     o:["The agent playground in the Foundry portal",
        "A production deployment slot",
        "The Azure pricing calculator",
        "The tenant properties blade"],
     a:0, d:3,
     x:"The agent playground is where you experiment with and test agents, including tool behavior, prior to coding against the Project API."},
    {q:"Which is a TRUE statement about how the Foundry Agent Service relates to models?",
     o:["Agents replace models entirely",
        "An agent references a deployed model for language understanding and reasoning",
        "Agents run models locally in the browser",
        "Each model may serve only one agent"],
     a:1, d:3,
     x:"An agent's 'brain' is a model it references for understanding and reasoning; instructions and tools complete the agent."},
    {q:"A developer complains: 'The playground works, but my code gets 401 errors on responses.create().' Which pair of values should they verify FIRST?",
     o:["Temperature and max tokens",
        "The endpoint URL (base_url) and the API key",
        "The billing account owner and invoice ID",
        "The agent's flag colors"],
     a:1, d:3,
     x:"401 = authentication failure — check the base_url and api_key used to build the client. Parameters affect content, not auth."},
    {q:"Which option lists the THREE levers for configuring generative model behavior at request time?",
     o:["Instructions, user input, parameters",
        "Region, SKU, tier",
        "Tenant, subscription, resource group",
        "Firewall, VNet, NSG"],
     a:0, d:3,
     x:"You shape behavior via instructions (system prompt), the user prompt itself, and parameters such as temperature and response length."}
  ]
};
