window.BANKS = window.BANKS || {};
window.BANKS.q2b = {
  title: "Quiz 2B — Generative AI & Agents (round 2)",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Which is the most accurate description of generative AI?",
     o:["It uses a language model to create original content in response to a prompt",
        "It is an obsolete form of AI replaced by machine learning",
        "It can only be operated by professional data scientists",
        "It retrieves pre-written answers from a database"],
     a:0, d:1,
     x:"Generative AI creates original content from prompts via a language model. It's neither obsolete nor specialist-only, and it doesn't just look up canned answers."},
    {q:"What is a token in the context of language models?",
     o:["A unit of text (a word or word-part) that the model processes",
        "A hardware security device",
        "A billing credit for API calls",
        "A synonym for an API key"],
     a:0, d:1,
     x:"Models split text into tokens — words or word-parts — which are then embedded and processed."},
    {q:"Which prompt element sets overall context and guidelines for how a model should respond?",
     o:["The system prompt (instructions)","The response body","The rate limit","The resource tag"],
     a:0, d:1,
     x:"Instructions/system prompts specify context and behavioral guidelines for the model's responses."},
    {q:"An agent's 'tools' serve which two purposes?",
     o:["Finding knowledge and performing actions",
        "Compiling code and formatting disks",
        "Billing and monitoring",
        "Authentication and encryption"],
     a:0, d:1,
     x:"Tools let agents find knowledge (context/grounding) and perform actions (task automation)."},
    {q:"Smart chatbots powered by generative AI differ from older chatbots because they:",
     o:["Generate responses dynamically instead of using hard-coded answers",
        "Only work by telephone",
        "Cannot understand questions",
        "Require no model at all"],
     a:0, d:1,
     x:"Generative chatbots produce answers dynamically from a model rather than following hard-coded scripts and logic."},
    {q:"Which family of API does Foundry expose for consuming generative models from code?",
     o:["OpenAI-compatible APIs","FTP APIs","SMTP APIs","Direct SQL queries"],
     a:0, d:1,
     x:"You consume Foundry generative models via OpenAI-compatible APIs (typically through SDKs)."},
    {q:"Which parameter most directly limits how long a model's answer can be?",
     o:["Maximum response length / max tokens","Temperature","Deployment region","API version"],
     a:0, d:1,
     x:"Response-length (max token) parameters cap output size; temperature controls randomness, not length."},
    {q:"Agentic AI is best described as:",
     o:["Automation through smart, connected agents built on generative AI",
        "A spreadsheet plug-in",
        "A way to compress models",
        "Manual scripting of business rules"],
     a:0, d:1,
     x:"Generative AI is the foundation for agentic AI — automation through smart, connected agents."},
    // ---- MODERATE (7) ----
    {q:"Where do embedding values come from during model training?",
     o:["They are hand-written by engineers",
        "They are learned, with attention weighing each token's relationship to surrounding tokens in training data",
        "They are copied from a dictionary",
        "They are random and never change"],
     a:1, d:2,
     x:"Embedding values are learned during training; attention encodes each token's contextual relationships with the tokens around it."},
    {q:"Which statement correctly contrasts LLMs and SLMs?",
     o:["SLMs are compact models suited to devices; LLMs are larger and more capable",
        "SLMs only handle images",
        "LLMs run only on phones",
        "There is no difference"],
     a:0, d:2,
     x:"Small language models trade capability for footprint, fitting devices and constrained environments; LLMs are larger."},
    {q:"You want repeatable demo output from a model. Which parameter should be LOWERED?",
     o:["Temperature","Max tokens","TPM rate limit","Number of tools"],
     a:0, d:2,
     x:"Lower temperature reduces randomness, making outputs more deterministic and repeatable."},
    {q:"In the OpenAI responses API call, the 'model' argument for a Foundry deployment should be set to:",
     o:["Your model deployment name","The literal string 'gpt'","The subscription ID","The tenant domain"],
     a:0, d:2,
     x:"You pass the deployment name you assigned when deploying the model in your project."},
    {q:"Which action turns a tuned playground configuration into a reusable agent?",
     o:["Saving the model configuration as a named agent",
        "Exporting the chat as PDF",
        "Deleting the project",
        "Lowering the rate limit"],
     a:0, d:2,
     x:"Foundry lets you save a model configuration as a named agent, or you can build the agent directly in the Agent Service."},
    {q:"The Foundry Project API authenticates with DefaultAzureCredential in the sample pattern. What does this represent?",
     o:["Microsoft Entra ID-based authentication resolved from the running environment",
        "A hard-coded password",
        "Anonymous access",
        "A GPU reservation"],
     a:0, d:2,
     x:"DefaultAzureCredential acquires a Microsoft Entra ID token from the environment (login, managed identity, etc.) — no key in code."},
    {q:"Which pairing of provider category and billing is correct for Foundry Models?",
     o:["Microsoft-sold models — billed through your Azure subscription; partner/community models — purchased from third-party providers",
        "All models are free",
        "Partner models bill through Microsoft 365",
        "Microsoft models require a separate retail store account"],
     a:0, d:2,
     x:"Models sold directly by Microsoft bill via the Azure subscription; partner and community models are purchased from the third parties."},
    // ---- HARD (15) ----
    {q:"A prompt engineer notices the phrase 'bark' is interpreted as a dog sound in pet-related sentences but as tree covering in gardening text. Which mechanism enables this context sensitivity?",
     o:["Attention relating each token to its surrounding tokens",
        "A spelling dictionary",
        "The rate limiter",
        "Response streaming"],
     a:0, d:3,
     x:"Attention encodes contextual relationships, so the same token is represented differently depending on the tokens around it."},
    {q:"Which analogy for vector arithmetic in embedding space is aligned with how semantic models behave?",
     o:["dog + young ≈ puppy","dog + young ≈ database","cat − kitten ≈ airplane","vector math is impossible on embeddings"],
     a:0, d:3,
     x:"Embedding spaces capture semantic relationships, allowing arithmetic like dog + young ≈ puppy and cat + young ≈ kitten."},
    {q:"A regulated customer must ensure prompts and completions are processed only in a specific geography. Which deployment consideration addresses this?",
     o:["Deployment type — it controls where data is processed",
        "Temperature","Guardrails","System prompt"],
     a:0, d:3,
     x:"Deployment type determines where data is processed (and the payment model) — the setting to review for data-residency needs."},
    {q:"Your agent answers from stale policy files after HR uploads new ones. Which area of the agent's configuration should you check?",
     o:["The knowledge/tools configuration pointing at the data sources",
        "The temperature parameter",
        "The billing plan",
        "The palette colors of the playground"],
     a:0, d:3,
     x:"Knowledge tools define which data sources ground the agent — the file-search source must reference the updated files."},
    {q:"What does extra_body={\"agent\": {\"name\": ..., \"type\": \"agent_reference\"}} accomplish in a responses.create() call?",
     o:["It routes the request to a named Foundry agent instead of a bare model",
        "It doubles the token limit",
        "It disables authentication",
        "It converts the response to XML"],
     a:0, d:3,
     x:"The agent_reference tells the Project API's OpenAI client to run the request through the named agent (with its instructions and tools)."},
    {q:"A team compares three catalog models for summarization quality and cost before deploying. Which Foundry capability supports this directly?",
     o:["The model catalog's discover / filter / compare features",
        "The tenant switcher",
        "Resource locks",
        "The activity log"],
     a:0, d:3,
     x:"The catalog is a central hub to discover, filter, and compare models from multiple providers before deployment."},
    {q:"Which situation calls for creating an AGENT rather than calling a model directly?",
     o:["The solution must autonomously look up order data and issue refunds via connected tools",
        "You need one-off text completion in a script",
        "You want to lower response randomness",
        "You need to change the JSON schema of a response"],
     a:0, d:3,
     x:"When the solution needs autonomy plus tools (knowledge + actions), that's the agent pattern; a direct model call suffices for simple completion."},
    {q:"An exam question shows code that only does: client = OpenAI(base_url=..., api_key=...). What has this code achieved so far?",
     o:["It created a client object bound to the endpoint — no prompt has been sent yet",
        "It generated a model response",
        "It deployed a new model",
        "It created a Foundry project"],
     a:0, d:3,
     x:"Instantiating the client configures connection + auth. Only responses.create() (or similar) actually sends a prompt."},
    {q:"Why do organizations pin a model VERSION rather than always auto-updating?",
     o:["To keep behavior stable and re-validate before adopting new versions",
        "Because new versions cost nothing",
        "Because auto-update disables the endpoint",
        "Version pinning is required for JSON output"],
     a:0, d:3,
     x:"Pinning gives predictable behavior; teams validate new versions before switching. The version setting includes the auto-update policy."},
    {q:"A junior developer sets temperature to the maximum for a legal-summary bot and users report inconsistent, embellished summaries. What is the BEST fix?",
     o:["Lower the temperature so output is more focused and deterministic",
        "Increase max tokens",
        "Remove the system prompt",
        "Switch the response format to plain text"],
     a:0, d:3,
     x:"High temperature increases randomness/creativity — inappropriate for precision tasks like legal summaries; lower it."},
    {q:"Which statement about multi-agent workflows is TRUE?",
     o:["Specialized agents can each own a responsibility and hand work to one another",
        "Only two agents may ever interact",
        "Agents cannot share a project",
        "Multi-agent systems remove the need for models"],
     a:0, d:3,
     x:"Agents collaborate with other agents — workflows chain specialized agents, each with its own role and tools."},
    {q:"The playground shows excellent answers, but production code with identical settings misbehaves. Which explanation is MOST plausible?",
     o:["The code targets a different deployment, or omits the instructions/parameters used in the playground",
        "Playgrounds use a secret superior model",
        "JSON responses randomize behavior",
        "API keys change model quality"],
     a:0, d:3,
     x:"Behavior differences usually mean the code isn't reproducing the playground configuration — deployment name, system prompt, or parameters differ."},
    {q:"Which capability distinguishes an agent's ACTION tools from its KNOWLEDGE tools?",
     o:["Actions change external state (create tickets, send mail); knowledge retrieves information to ground responses",
        "Actions are read-only; knowledge is write-only",
        "Actions run before the model; knowledge after",
        "There is no distinction"],
     a:0, d:3,
     x:"Knowledge tools fetch information for context; action tools automate tasks by operating on connected services."},
    {q:"For an internal hackathon, students need to call a deployed Foundry model from Python quickly. Which minimal artifact set do they need?",
     o:["Endpoint URL, API key, deployment name, openai package",
        "Domain controller access and a VPN",
        "The model's training corpus",
        "A Kubernetes cluster"],
     a:0, d:3,
     x:"The OpenAI SDK client needs the endpoint, a key (or token), and the deployment name — nothing heavier."},
    {q:"An auditor asks how you prevent your deployed model from producing harmful categories of content organization-wide. Your BEST answer references:",
     o:["Guardrails — responsible AI policies applied to the model deployment",
        "Raising temperature",
        "Hiding the playground",
        "Renaming the resource group"],
     a:0, d:3,
     x:"Guardrails attach responsible-AI content policies at the deployment, enforcing content rules regardless of the calling app."}
  ]
};
