window.BANKS = window.BANKS || {};
window.BANKS.q3a = {
  title: "Quiz 3A — NLP & Text Analysis",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"What is the purpose of tokenization in NLP?",
     o:["To break text into smaller units for analysis",
        "To translate text into another language",
        "To encrypt sensitive documents",
        "To compress text for storage"],
     a:0, d:1,
     x:"Tokenization splits text into words or word-parts so it can be analyzed or vectorized."},
    {q:"Which NLP task determines whether a product review is positive or negative?",
     o:["Sentiment analysis","Language detection","Named entity recognition","Stemming"],
     a:0, d:1,
     x:"Sentiment analysis is a text-classification task that evaluates tone/opinion."},
    {q:"Named entity recognition (NER) identifies which items in text?",
     o:["People, places, organizations, dates and similar entities",
        "Grammatical errors",
        "Font styles",
        "Passwords"],
     a:0, d:1,
     x:"NER labels entities such as persons, organizations, locations, and dates found in text."},
    {q:"'The', 'a', 'it', and 'and' are examples of what in text pre-processing?",
     o:["Stop words","Phonemes","Embeddings","Key phrases"],
     a:0, d:1,
     x:"Stop words are common 'noise' words removed during pre-processing because they add little meaning."},
    {q:"Which technique consolidates 'power', 'powered' and 'powerful' into a shared root?",
     o:["Stemming / lemmatization","Tokenization","Normalization","POS tagging"],
     a:0, d:1,
     x:"Stemming and lemmatization reduce word variants to a common root form."},
    {q:"Parts-of-speech (POS) tagging labels words as:",
     o:["Verbs, nouns, adjectives, and other word types",
        "Positive or negative",
        "English or French",
        "Long or short"],
     a:0, d:1,
     x:"POS tagging identifies each token's grammatical role — verb, noun, adjective, etc."},
    {q:"Which pre-processing step removes capitalization and punctuation?",
     o:["Normalization","Stop-word removal","Vectorization","Summarization"],
     a:0, d:1,
     x:"Normalization standardizes text by lower-casing and stripping punctuation."},
    {q:"Which of these is a common NLP use case?",
     o:["Spam filtering in email systems","Rendering 3D game scenes","Defragmenting hard disks","Encrypting network traffic"],
     a:0, d:1,
     x:"NLP powers spam filtering, search indexing, chatbot intent prediction, PII redaction, and social-media analysis."},
    // ---- MODERATE (7) ----
    {q:"Which technique measures a word's importance to one document relative to its frequency across an entire collection?",
     o:["TF-IDF","Bag-of-Words","TextRank","Naïve Bayes"],
     a:0, d:2,
     x:"Term Frequency–Inverse Document Frequency scores words high when frequent in a document but rare across the corpus."},
    {q:"Bag-of-Words classification works by:",
     o:["Correlating the frequency of words from a defined set with a category",
        "Translating text into vectors of pixels",
        "Sorting words alphabetically",
        "Counting sentences only"],
     a:0, d:2,
     x:"BoW correlates word-set frequencies with classifications — e.g., 'happy/great/fantastic' indicating positive sentiment."},
    {q:"TextRank is commonly used for which purpose, and what inspired it?",
     o:["Extractive summarization; based on the PageRank web-search idea",
        "Machine translation; based on RSA encryption",
        "Speech synthesis; based on MP3 encoding",
        "Spam detection; based on firewalls"],
     a:0, d:2,
     x:"TextRank scores sentence relevance (a PageRank-style algorithm) and is used to extract the n most relevant sentences as a summary."},
    {q:"What best describes the role of embedding vectors in NLP?",
     o:["They capture semantic relationships between tokens in multiple dimensions",
        "They duplicate tokens in several languages",
        "They define which stop words to ignore",
        "They store the alphabet"],
     a:0, d:2,
     x:"Embeddings represent tokens as multidimensional vectors capturing meaning — the basis of modern semantic models and LLMs."},
    {q:"Azure Language in Foundry Tools offers which capability set?",
     o:["PII extraction, language detection, named entity recognition, Text Analytics for Health",
        "Video rendering and 3D capture",
        "GPU scheduling",
        "Database indexing"],
     a:0, d:2,
     x:"Azure Language provides PII extraction, language detection, NER, and health-domain text analytics as prebuilt capabilities."},
    {q:"What does client.detect_language([text]) return?",
     o:["Language name, ISO 639-1 code, and a confidence score",
        "A translated document",
        "The text with all verbs removed",
        "A list of stop words"],
     a:0, d:2,
     x:"Language detection returns the detected language name, its ISO 639-1 code, and a 0–1 confidence score."},
    {q:"What is the purpose of the client object in the Azure Language SDK?",
     o:["It lets application code communicate with the Azure Language service",
        "It stores the analyzed text permanently",
        "It configures the app's UI theme",
        "It trains a new language model"],
     a:0, d:2,
     x:"The client object (e.g., TextAnalyticsClient) wraps the endpoint + credentials so your code can call the service."},
    // ---- HARD (15) ----
    {q:"A compliance pipeline must return IDENTICAL structured results every time the same contract is analyzed, with confidence scores. Which approach is correct?",
     o:["Azure Language SDK — deterministic structured output",
        "Prompting a general-purpose LLM",
        "The chat playground",
        "Manual review only"],
     a:0, d:3,
     x:"Azure Language returns deterministic, structured results with confidence metrics. LLM prompting is probabilistic and may vary between calls."},
    {q:"An analyst wants ONE call that simultaneously summarizes a review, lists its key complaints, and drafts a polite reply. Which approach fits BEST?",
     o:["A general-purpose model prompt combining the tasks",
        "The Azure Language detect_language method",
        "recognize_pii_entities",
        "A TF-IDF batch job"],
     a:0, d:3,
     x:"General-purpose models excel at flexible, conversational analysis combining multiple tasks in one call — something the fixed Language APIs don't do."},
    {q:"recognize_pii_entities() is preferred over an LLM prompt for redacting customer records because it provides:",
     o:["Redacted text plus per-entity categories and confidence scores, deterministically",
        "More creative rewording",
        "Longer responses",
        "Automatic translation"],
     a:0, d:3,
     x:"For regulated data you want deterministic redaction with confidence per entity — exactly what the PII API returns."},
    {q:"Why can TF alone mislead when identifying a document's distinctive topics, and how does TF-IDF fix it?",
     o:["Common corpus-wide words dominate raw counts; IDF down-weights words frequent across all documents",
        "TF ignores capital letters; IDF restores them",
        "TF counts sentences; IDF counts paragraphs",
        "TF works only in English"],
     a:0, d:3,
     x:"Words common everywhere (e.g., 'company') score high on TF in every document; dividing by document frequency (IDF) surfaces terms distinctive to this document."},
    {q:"Which statement about the Azure Language MCP server is TRUE?",
     o:["It exposes Azure Language capabilities to agents through the Model Context Protocol",
        "It replaces the generative model inside an agent",
        "It generates website layouts",
        "It is required for all text analysis"],
     a:0, d:3,
     x:"The MCP server makes Azure Language functions callable as agent tools; the agent's model remains responsible for reasoning."},
    {q:"When connecting the Azure Language tool to an agent, which approval options exist for tool access?",
     o:["One-time, always for this tool, or always for all tools",
        "Per-word approval only",
        "No approval is ever needed",
        "Only tenant admins may approve, per call"],
     a:0, d:3,
     x:"Foundry prompts you to approve tool access one-time, always for that tool, or always for all tools."},
    {q:"A dataset of multilingual support tickets must first be routed to language-specific teams. Which method call fits?",
     o:["client.detect_language(documents)","client.extract_key_phrases(documents)","client.analyze_sentiment(documents)","client.recognize_entities(documents)"],
     a:0, d:3,
     x:"Language detection identifies each ticket's language (name, ISO code, confidence) so it can be routed correctly."},
    {q:"Which is a CORRECT ordering of a typical statistical text-analysis flow?",
     o:["Tokenize → normalize → remove stop words → stem → analyze frequencies",
        "Analyze frequencies → tokenize → stem → normalize",
        "Stem → summarize → tokenize → tag",
        "Remove stop words → capture audio → tokenize"],
     a:0, d:3,
     x:"Pre-processing (tokenization, normalization, stop-word removal, stemming) prepares tokens before frequency-based analysis."},
    {q:"A marketing team asks why the LLM's entity list for the same press release differed slightly between Monday and Tuesday runs. The BEST explanation:",
     o:["LLM generation is probabilistic, so outputs can vary; a deterministic Language API would not",
        "The press release file was corrupted",
        "Azure regions rotate nightly",
        "JSON cannot represent entities"],
     a:0, d:3,
     x:"Probabilistic generation is the documented trade-off of using general-purpose models for analysis; Azure Language is the deterministic alternative."},
    {q:"In the Azure Language SDK, what is passed to recognize_entities()?",
     o:["A collection (list) of documents to analyze",
        "A single character",
        "The endpoint URL",
        "A trained model file"],
     a:0, d:3,
     x:"You submit a collection of documents; results are returned per document with entities, categories, and confidence scores."},
    {q:"A hospital wants entities like medication names and dosages extracted from clinical notes. Which Azure Language capability is designed for this?",
     o:["Text Analytics for Health","Key-phrase extraction","Language detection","Spell check"],
     a:0, d:3,
     x:"Text Analytics for Health specializes in clinical/medical entity extraction from unstructured health text."},
    {q:"Which is TRUE about combining approaches in one solution?",
     o:["You can use Azure Language for deterministic PII redaction, then prompt an LLM on the redacted text for flexible analysis",
        "The two approaches cannot coexist in one app",
        "LLMs must always run before any API",
        "PII detection requires an agent"],
     a:0, d:3,
     x:"A common production pattern: deterministic redaction first (compliance), then flexible LLM analysis on safe text."},
    {q:"Your extractive summarizer must pick the 3 most relevant sentences from each article. Which technique matches?",
     o:["TextRank sentence scoring","Bag-of-Words","Stop-word removal","Language detection"],
     a:0, d:3,
     x:"TextRank scores sentence relevance from shared terms and is commonly used to extract the top n sentences."},
    {q:"Which statement about semantic models vs statistical techniques is TRUE?",
     o:["Semantic models vectorize tokens to capture meaning, and are the basis of modern LLMs; statistical methods rely on token counts",
        "Statistical methods understand meaning; semantic models count words",
        "Both are identical in mechanism",
        "Semantic models cannot be trained"],
     a:0, d:3,
     x:"Statistical analysis (TF, TF-IDF, BoW) counts tokens; semantic models embed tokens as vectors trained to encapsulate relationships — the LLM foundation."},
    {q:"An exam scenario: 'Structured results based on statistical techniques, same input → same output.' Which option should you eliminate FIRST and why?",
     o:["The chat playground — interactive LLM chat is neither structured nor deterministic",
        "The Azure Language SDK — it is too deterministic",
        "REST APIs — they cannot return JSON",
        "Nothing can satisfy the requirement"],
     a:0, d:3,
     x:"Playground chat is exploratory and probabilistic. The Azure Language SDK is the fit; REST/JSON support structured output fine."}
  ]
};
