window.BANKS = window.BANKS || {};
window.BANKS.q3b = {
  title: "Quiz 3B — NLP & Text Analysis (round 2)",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Natural language processing (NLP) is best summarized as:",
     o:["Inferring meaning from text",
        "Rendering fonts on screen",
        "Compressing documents",
        "Encrypting messages"],
     a:0, d:1,
     x:"NLP is the workload concerned with understanding and inferring meaning from written language."},
    {q:"Which task produces a short version of a long document?",
     o:["Summarization","Tokenization","POS tagging","Language detection"],
     a:0, d:1,
     x:"Summarization condenses a document; extractive approaches pick the most relevant sentences."},
    {q:"PII stands for:",
     o:["Personally identifiable information","Public internet index","Partial input inference","Primary integer identifier"],
     a:0, d:1,
     x:"PII = personally identifiable information — names, addresses, ID numbers, emails, etc."},
    {q:"Which of these is an example of a named entity?",
     o:["'Microsoft' (an organization)","'quickly' (an adverb)","A comma","A blank line"],
     a:0, d:1,
     x:"Named entities are real-world items — organizations, people, places, dates — like 'Microsoft'."},
    {q:"Key-phrase extraction answers which question about a document?",
     o:["What are the main topics or talking points?",
        "Who wrote it?",
        "How many bytes is it?",
        "What font does it use?"],
     a:0, d:1,
     x:"Key-phrase extraction surfaces the main concepts/terms in a document."},
    {q:"Which Python package provides TextAnalyticsClient?",
     o:["azure.ai.textanalytics","numpy","matplotlib","flask"],
     a:0, d:1,
     x:"The Azure Language SDK's TextAnalyticsClient comes from the azure.ai.textanalytics library."},
    {q:"A chatbot deciding a user wants to 'book a flight' from their message is an example of:",
     o:["Intent prediction","Speech synthesis","Image classification","OCR"],
     a:0, d:1,
     x:"Intent prediction — an NLP use case — maps user utterances to intended actions for bots and assistants."},
    {q:"Which credential object authenticates TextAnalyticsClient with a key?",
     o:["AzureKeyCredential","StorageSharedKey","X509Certificate","BasicAuthHeader"],
     a:0, d:1,
     x:"AzureKeyCredential wraps the resource key; alternatively Microsoft Entra ID credentials can be used."},
    // ---- MODERATE (7) ----
    {q:"Why remove stop words before statistical analysis?",
     o:["They occur everywhere and add noise, diluting meaningful frequency signals",
        "They contain personal data",
        "They break JSON encoding",
        "They are illegal in some locales"],
     a:0, d:2,
     x:"Stop words are high-frequency, low-information words; removing them sharpens topic and classification signals."},
    {q:"Which output would you expect from analyzing: 'Priya from Contoso visited Delhi on March 3rd' with NER?",
     o:["Priya (person), Contoso (organization), Delhi (location), March 3rd (date)",
        "A sentiment score of 0.99",
        "A French translation",
        "A list of stop words"],
     a:0, d:2,
     x:"NER labels each detected entity with a category — person, organization, location, date."},
    {q:"Which statement about general-purpose models for text analysis is TRUE?",
     o:["They can be prompted to do key-term extraction, entity recognition, sentiment, and summarization",
        "They can only chat casually",
        "They always return confidence scores per entity",
        "They guarantee identical output per call"],
     a:0, d:2,
     x:"LLMs can be prompted into any of these tasks flexibly — the trade-off is probabilistic, unstructured output."},
    {q:"A sentiment API returns 'mixed' with document- and sentence-level scores. What advantage does this structured output give a production system?",
     o:["Programmatic routing/thresholds without parsing free text",
        "Prettier emails",
        "Lower network latency only",
        "It removes the need for storage"],
     a:0, d:2,
     x:"Structured results (labels + scores) can be consumed directly by code — no fragile parsing of natural-language answers."},
    {q:"In pre-processing, what does lemmatization do that simple stemming may not?",
     o:["Maps words to proper dictionary roots (e.g., 'better' → 'good') rather than just trimming suffixes",
        "Removes punctuation",
        "Counts word frequency",
        "Translates the text"],
     a:0, d:2,
     x:"Lemmatization uses vocabulary/morphology to find true base forms; stemming just chops endings."},
    {q:"Which choice pairs a use case with the RIGHT approach?",
     o:["Regulated PII redaction → Azure Language; exploratory review analysis → general-purpose model",
        "Regulated PII redaction → chat playground; production pipeline → manual notes",
        "Deterministic pipeline → maximum temperature LLM",
        "Confidence scores → free-form prose"],
     a:0, d:2,
     x:"Regulated/deterministic → Azure Language; flexible/exploratory → prompt an LLM."},
    {q:"The Word2Vec family of techniques is associated with:",
     o:["Learning semantic vector representations (embeddings) of words",
        "Counting term frequency only",
        "Optical character recognition",
        "Audio waveform encoding"],
     a:0, d:2,
     x:"Word2Vec pioneered learned word embeddings — semantic vectors — as opposed to count-based statistics like TF-IDF."},
    // ---- HARD (15) ----
    {q:"A news site auto-categorizes articles into Sports/Politics/Tech using frequencies of hand-picked indicator words. Which classic technique is this?",
     o:["Bag-of-Words classification","TextRank","Prosody generation","Semantic segmentation"],
     a:0, d:3,
     x:"Correlating frequencies of a word set with categories is Bag-of-Words classification."},
    {q:"The same 500 support emails are analyzed nightly; results feed automated dashboards, and auditors demand reproducibility. A developer proposes GPT prompting. What is the STRONGEST objection?",
     o:["Probabilistic generation may give different results between runs, breaking reproducibility",
        "LLMs cannot read emails",
        "GPT models return XML only",
        "Dashboards cannot display LLM output"],
     a:0, d:3,
     x:"For audited, repeatable pipelines the documented trade-off of LLMs — run-to-run variation — is disqualifying; use Azure Language."},
    {q:"Which line correctly creates an Azure Language client?",
     o:["client = TextAnalyticsClient(endpoint=ep, credential=AzureKeyCredential(key))",
        "client = TextAnalyticsClient(key=ep, url=key)",
        "client = OpenAI(model='language')",
        "client = AzureKeyCredential(endpoint)"],
     a:0, d:3,
     x:"TextAnalyticsClient takes the service endpoint and a credential object (key or Entra ID)."},
    {q:"After running recognize_pii_entities on 'Call me at 555-0142', what should the redacted text look like?",
     o:["'Call me at ************' with the phone number masked",
        "The original text unchanged",
        "An empty string",
        "A rhyming poem"],
     a:0, d:3,
     x:"The PII API returns redacted text with detected PII values masked, plus the entity list and confidence scores."},
    {q:"A team building an agent wants it to call Azure Language for entity extraction mid-conversation. Which integration and protocol are involved?",
     o:["Connect the Azure Language in Foundry Tools MCP server as an agent tool (Model Context Protocol)",
        "Give the agent the resource's connection string in the prompt",
        "Export entities to CSV manually",
        "Retrain the base model"],
     a:0, d:3,
     x:"The MCP server exposes Azure Language capabilities as callable tools for agents — with configured resource and credentials."},
    {q:"Why does TF-IDF beat raw TF for search indexing across a large corpus?",
     o:["It highlights terms that characterize a document rather than terms common to every document",
        "It runs on GPUs only",
        "It ignores rare words entirely",
        "It requires no tokenization"],
     a:0, d:3,
     x:"IDF suppresses corpus-wide common terms and boosts distinctive ones — better matching of documents to distinctive queries."},
    {q:"Which analysis flow correctly describes semantic similarity search over documents?",
     o:["Embed documents and query as vectors, then compare vector similarity",
        "Sort documents alphabetically and binary-search",
        "Count commas per paragraph",
        "Hash each file with SHA-256 and compare digests"],
     a:0, d:3,
     x:"Semantic search embeds text into vector space; similar meanings yield nearby vectors regardless of exact wording."},
    {q:"A junior dev prompts an LLM: 'Extract entities as JSON.' Sometimes the reply includes commentary that breaks the JSON parser. Which mitigation aligns with course guidance?",
     o:["Use the Azure Language SDK for guaranteed structured output in the pipeline",
        "Parse harder with regex forever",
        "Ban JSON",
        "Raise temperature so it varies more"],
     a:0, d:3,
     x:"When structure matters, use the deterministic service; LLM output structure is not guaranteed."},
    {q:"Which scenario matches Text Analytics for Health rather than generic NER?",
     o:["Extracting drug names, dosages, and diagnoses from discharge summaries",
        "Finding city names in travel blogs",
        "Detecting French vs Spanish",
        "Counting adjectives"],
     a:0, d:3,
     x:"The health capability specializes in clinical entities (medications, dosages, conditions) that generic NER handles poorly."},
    {q:"Your pipeline detects language, then routes English texts to sentiment and others to translation. What structured fields from detect_language make the routing reliable?",
     o:["ISO 639-1 code and confidence score",
        "The document's word count",
        "The service region",
        "The API version string"],
     a:0, d:3,
     x:"The ISO code identifies the language programmatically, and the confidence score lets you set a routing threshold."},
    {q:"An exam item claims: 'The client object stores the text to be analyzed.' Why is this WRONG?",
     o:["The client wraps connection + credentials; documents are passed per method call",
        "Clients store text but only in XML",
        "It is actually correct",
        "Clients can only store one sentence"],
     a:0, d:3,
     x:"The client is the communication object; text goes in as arguments to methods like recognize_entities(documents=...)."},
    {q:"A social team wants trend detection across millions of posts daily with consistent metrics month over month. Rank the PRIMARY requirement and the matching tech:",
     o:["Determinism at scale → Azure Language batch analysis",
        "Creativity → maximum-temperature LLM",
        "Human review of each post",
        "Manual spreadsheets"],
     a:0, d:3,
     x:"Consistent longitudinal metrics require deterministic, scalable analysis — Azure Language's strength."},
    {q:"Which statement about combining tasks in ONE LLM call is TRUE?",
     o:["An LLM prompt can request sentiment, key phrases, and a summary together; dedicated APIs would need separate calls",
        "Dedicated APIs always combine tasks automatically",
        "LLMs may only do one task per day",
        "Combining tasks requires MCP"],
     a:0, d:3,
     x:"Multi-task-in-one-call flexibility is a documented advantage of general-purpose models."},
    {q:"For 'article categorization on web sites and feeds', which pair of techniques could implement it, simplest first?",
     o:["Bag-of-Words classification, or embedding-based semantic classification",
        "OCR then diffusion",
        "Prosody then phoneme mapping",
        "Bounding boxes then segmentation"],
     a:0, d:3,
     x:"Categorization can be count-based (BoW) or semantic (embeddings); the other options belong to speech/vision workloads."},
    {q:"A colleague says 'embeddings duplicate tokens in multiple languages.' Correct the statement.",
     o:["Embeddings are vector representations capturing semantic token relationships in multiple dimensions — not duplicates or translations",
        "The statement is accurate",
        "Embeddings are stop-word lists",
        "Embeddings are just longer tokens"],
     a:0, d:3,
     x:"Embeddings encode meaning as multidimensional vectors; they neither duplicate nor translate tokens."}
  ]
};
