window.BANKS = window.BANKS || {};
window.BANKS.q4a = {
  title: "Quiz 4A — AI Speech",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Speech-to-text (STT) is also known as:",
     o:["Speech recognition","Speech synthesis","Prosody generation","Language modeling"],
     a:0, d:1,
     x:"STT = speech recognition: audio input becomes text output. TTS = speech synthesis: text becomes audio."},
    {q:"What are phonemes?",
     o:["The smallest units of sound in speech",
        "AI models that generate audio",
        "Artifacts removed during noise clean-up",
        "Musical notation symbols"],
     a:0, d:1,
     x:"Phonemes are the smallest sound units of word-parts — the units acoustic models map audio features to."},
    {q:"Which input sources can speech recognition accept?",
     o:["Audio files, streams, or a microphone",
        "Only WAV files",
        "Only landline telephones",
        "Text documents"],
     a:0, d:1,
     x:"STT input can come from an audio file, an audio stream, or live microphone capture."},
    {q:"Text-to-speech outputs what?",
     o:["An audio waveform of spoken speech","A text transcription","A JSON entity list","An image"],
     a:0, d:1,
     x:"TTS converts text into an audio waveform — synthesized speech."},
    {q:"Automatic subtitles for videos are an accessibility use case of:",
     o:["Speech-to-text","Text-to-speech","Image classification","OCR"],
     a:0, d:1,
     x:"Captions/subtitles transcribe spoken audio — a speech recognition (STT) use case."},
    {q:"A screen reader that voices on-screen text aloud uses:",
     o:["Text-to-speech","Speech-to-text","Named entity recognition","Semantic segmentation"],
     a:0, d:1,
     x:"Screen readers synthesize speech from text — TTS."},
    {q:"Which Foundry feature lets you try real-time transcription without writing code?",
     o:["The Foundry portal speech playground","The billing page","Azure CLI","Resource tags"],
     a:0, d:1,
     x:"The portal playground lets you experiment with speech-to-text (and text-to-speech voices) interactively."},
    {q:"Which is a common TTS use case?",
     o:["Notifications and alerts read aloud","Meeting transcription","Voice-mail transcription","Subtitling a lecture"],
     a:0, d:1,
     x:"TTS speaks text: alerts, e-learning narration, chatbot voices. The other three transcribe audio (STT)."},
    // ---- MODERATE (7) ----
    {q:"What happens during the pre-processing stage of speech recognition?",
     o:["Feature vectors are extracted from the audio waveform for modeling",
        "Background noise is added to the signal",
        "The audio is converted to a video format",
        "The text is translated"],
     a:0, d:2,
     x:"Pre-processing featurizes the signal — intensity at specific frequencies becomes feature vectors. Noise is removed, never added."},
    {q:"In speech recognition, what does the acoustic model do?",
     o:["Maps audio features to phonemes",
        "Predicts word sequences",
        "Formats the final text",
        "Captures the analog signal"],
     a:0, d:2,
     x:"The acoustic model converts feature vectors into phonemes; the language model then predicts the word sequence."},
    {q:"In speech recognition, what does the language model contribute?",
     o:["It predicts the most probable word sequence from the phonemes",
        "It amplifies quiet audio",
        "It selects a synthetic voice",
        "It compresses the waveform"],
     a:0, d:2,
     x:"Given candidate phoneme interpretations, the language model picks the likeliest words — 'nice to be here' over 'nights two bee hear'."},
    {q:"Why is prosody generation important in speech synthesis?",
     o:["It ensures natural pronunciation and speech cadence",
        "It maximizes output volume",
        "It translates speech for the listener",
        "It encrypts the audio"],
     a:0, d:2,
     x:"Prosody adjusts pitch, timbre, and rhythm so synthesized speech sounds natural — not louder or translated."},
    {q:"During TTS normalization, '3:00pm' typically becomes:",
     o:["'three o'clock P M'","'3 3 3'","'fifteen hundred hours' always","It is deleted"],
     a:0, d:2,
     x:"Normalization expands abbreviations and numbers into speakable words before phoneme mapping."},
    {q:"Which SDK class configures the key and endpoint for Azure Speech?",
     o:["SpeechConfig","AudioConfig","SpeechRecognizer","VoiceProfile"],
     a:0, d:2,
     x:"SpeechConfig(subscription=key, endpoint=...) holds the connection settings; AudioConfig selects the audio source/sink."},
    {q:"In the Speech SDK, AudioConfig(filename='msg.wav') specifies:",
     o:["The audio source to transcribe (a file rather than the microphone)",
        "The output voice name",
        "The billing account",
        "The text to synthesize"],
     a:0, d:2,
     x:"AudioConfig points the recognizer at its audio source — here a .wav file instead of default microphone input."},
    // ---- HARD (15) ----
    {q:"Arrange the speech recognition pipeline correctly:",
     o:["Audio capture → pre-processing → acoustic modeling → language modeling → post-processing",
        "Language modeling → audio capture → acoustic modeling → pre-processing → post-processing",
        "Pre-processing → audio capture → post-processing → acoustic modeling → language modeling",
        "Acoustic modeling → language modeling → audio capture → pre-processing → post-processing"],
     a:0, d:3,
     x:"Capture the waveform, extract features, map features to phonemes (acoustic), choose probable words (language), then normalize/format the text."},
    {q:"Arrange the speech synthesis pipeline correctly:",
     o:["Source text → normalization → linguistic modeling → prosody generation → waveform encoding",
        "Waveform encoding → prosody → normalization → linguistic modeling → text",
        "Normalization → waveform encoding → prosody → source text → linguistic modeling",
        "Source text → prosody → normalization → waveform → phonemes"],
     a:0, d:3,
     x:"Text is normalized, mapped to phonemes (linguistic modeling), given natural prosody, then encoded as an audio waveform."},
    {q:"A transcription result reads 'weather four cast' instead of 'weather forecast'. Which pipeline component most directly failed?",
     o:["The language model — it chose an improbable word sequence from the phonemes",
        "The waveform encoder",
        "Prosody generation",
        "The microphone driver's color profile"],
     a:0, d:3,
     x:"Homophone confusion is the language model's job to resolve — it should prefer the most probable word sequence."},
    {q:"Why would a developer use the Azure Speech SDK instead of only the Foundry playground?",
     o:["The SDK lets speech recognition be embedded directly into application code",
        "The SDK replaces the need for speech models",
        "The playground forbids audio files",
        "SDKs work without endpoints"],
     a:0, d:3,
     x:"The playground is for experimentation; production apps integrate speech via the SDK, which still calls deployed service endpoints."},
    {q:"In TTS code, no AudioConfig was created, yet synthesis works. Why?",
     o:["Default speaker output requires no AudioConfig; you'd add one to write audio to a file",
        "AudioConfig is deprecated",
        "The model guessed the output device",
        "TTS never uses audio configuration"],
     a:0, d:3,
     x:"Omitting AudioConfig sends synthesized audio to the default speaker; file output needs an explicit AudioConfig."},
    {q:"Which property selects the synthetic voice in the Speech SDK?",
     o:["speech_config.speech_synthesis_voice_name",
        "audio_config.filename",
        "recognizer.language_model",
        "speech_config.rate_limit"],
     a:0, d:3,
     x:"You assign a voice (e.g., a neural voice name) to speech_synthesis_voice_name on the SpeechConfig."},
    {q:"What does recognize_once_async().get() return in the STT pattern?",
     o:["A result object whose .text property holds the transcription",
        "A raw waveform",
        "A list of stop words",
        "The service invoice"],
     a:0, d:3,
     x:"The async recognition returns a result; result.text contains the recognized transcript."},
    {q:"What does the Azure Text-to-Speech SDK handle on the developer's behalf?",
     o:["Authentication, network communication, and audio generation",
        "Only voice selection",
        "Permanent audio archiving in Azure Storage",
        "Grammar correction of the input text"],
     a:0, d:3,
     x:"The SDK abstracts auth, transport, and synthesis; storage/archiving is the app's own concern."},
    {q:"Which Voice Live capabilities distinguish it from basic STT+TTS chaining?",
     o:["Continuous conversation flow with interruption handling and background-noise reduction, tied to a generative model with instructions and tools",
        "Higher audio bitrate only",
        "Free unlimited usage",
        "It removes the need for microphones"],
     a:0, d:3,
     x:"Voice Live provides real-time conversational speech with a generative model — interruptions and noise handling included."},
    {q:"What role does the Voice Live Python SDK (azure-ai-voicelive) play?",
     o:["It opens a real-time connection, streams audio, and handles spoken responses and interruptions",
        "It stores recordings permanently in Azure Storage",
        "It replaces the device's microphone and speakers",
        "It trains custom voices offline"],
     a:0, d:3,
     x:"The SDK manages the live bidirectional audio session for voice agents — streaming, responses, interruptions."},
    {q:"A hospital wants clinicians to dictate notes hands-free into the EHR. Map the need to the right capability:",
     o:["Speech-to-text (audio note-taking use case)",
        "Text-to-speech alerts",
        "Semantic segmentation",
        "Diffusion image generation"],
     a:0, d:3,
     x:"Dictation → transcription → STT; audio note-taking in healthcare is a listed STT use case."},
    {q:"Which agent-integration option exposes speech capabilities to Foundry agents?",
     o:["The Azure Speech in Foundry Tools MCP server",
        "A CSV export",
        "A VPN gateway",
        "Editing the agent's temperature"],
     a:0, d:3,
     x:"Like Azure Language, Azure Speech offers an MCP server so agents can use speech recognition/synthesis as tools."},
    {q:"'The pre-processing stage converts audio to .wmv format.' What is wrong with this claim?",
     o:["Pre-processing extracts feature vectors from the waveform; .wmv is a video container, not a recognition step",
        "Nothing — it is accurate",
        ".wmv is used but only for phone calls",
        "Pre-processing happens after language modeling"],
     a:0, d:3,
     x:"Recognition pre-processing is featurization of the signal, not media-format conversion."},
    {q:"A voice-banking app must speak balances aloud AND accept spoken commands, in one continuous, interruptible conversation. Which single Foundry capability fits BEST?",
     o:["Voice Live (real-time speech with a generative model)",
        "Batch transcription API",
        "The image playground",
        "TF-IDF"],
     a:0, d:3,
     x:"Bidirectional, continuous, interruptible voice conversation is exactly the Voice Live scenario — richer than separate STT/TTS calls."},
    {q:"Why does TTS normalization expand 'Dr.' to 'doctor' BEFORE phoneme mapping?",
     o:["Phoneme mapping needs speakable words; abbreviations would otherwise be spelled out or mispronounced",
        "To save storage",
        "Because phonemes only exist for medical terms",
        "To encrypt titles"],
     a:0, d:3,
     x:"Linguistic modeling maps normalized, speakable text to phonemes; un-expanded abbreviations and digits would map incorrectly."}
  ]
};
