window.BANKS = window.BANKS || {};
window.BANKS.q4b = {
  title: "Quiz 4B — AI Speech (round 2)",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Which pair correctly matches abbreviation to direction?",
     o:["STT = audio → text; TTS = text → audio",
        "STT = text → audio; TTS = audio → text",
        "Both convert text to audio",
        "Both convert audio to text"],
     a:0, d:1,
     x:"Speech-to-text transcribes audio; text-to-speech synthesizes audio from text."},
    {q:"Meeting and interview transcription is a use case of:",
     o:["Speech recognition","Speech synthesis","Image generation","Field extraction"],
     a:0, d:1,
     x:"Transcription converts spoken audio into text — speech recognition (STT)."},
    {q:"Video-game characters speaking dynamic dialogue lines use:",
     o:["Text-to-speech","Speech-to-text","OCR","POS tagging"],
     a:0, d:1,
     x:"Generating character voices from text is a listed TTS entertainment/media use case."},
    {q:"What does a digital waveform represent in speech processing?",
     o:["The captured audio signal in digital form",
        "The text transcript",
        "The GPU temperature",
        "A JSON schema"],
     a:0, d:1,
     x:"Audio capture converts the analog sound signal into a digital waveform for processing."},
    {q:"The Python package for the Azure Speech SDK is imported as:",
     o:["azure.cognitiveservices.speech","azure.storage.blob","openai.audio","numpy.speech"],
     a:0, d:1,
     x:"The Speech SDK is azure.cognitiveservices.speech (commonly aliased as speechsdk)."},
    {q:"Which SDK object actually performs speech-to-text?",
     o:["SpeechRecognizer","SpeechSynthesizer","AudioConfig","AzureKeyCredential"],
     a:0, d:1,
     x:"SpeechRecognizer (built from SpeechConfig + AudioConfig) performs recognition; SpeechSynthesizer performs TTS."},
    {q:"A voice-activated assistant that hears 'What's the weather?' first applies:",
     o:["Speech recognition to transcribe the question",
        "Speech synthesis",
        "Image classification",
        "Data normalization"],
     a:0, d:1,
     x:"The spoken question must be recognized (STT) before any language understanding or response."},
    {q:"Which method speaks a string through the synthesizer?",
     o:["speak_text_async('...').get()","recognize_once_async().get()","detect_language()","responses.create()"],
     a:0, d:1,
     x:"SpeechSynthesizer.speak_text_async() synthesizes and plays/writes the audio."},
    // ---- MODERATE (7) ----
    {q:"Which stage differs MOST between recognition and synthesis pipelines?",
     o:["Recognition ends by producing text; synthesis ends by encoding an audio waveform",
        "Both end with waveform encoding",
        "Both start from text",
        "Neither uses phonemes"],
     a:0, d:2,
     x:"They are mirror images: STT goes audio→features→phonemes→words→text; TTS goes text→phonemes→prosody→waveform."},
    {q:"Phonemes appear in BOTH pipelines. In synthesis, they are produced by:",
     o:["Linguistic modeling from normalized text",
        "The acoustic model from audio features",
        "The waveform encoder",
        "The billing meter"],
     a:0, d:2,
     x:"In TTS, linguistic modeling maps normalized text to phonemes. (In STT, the acoustic model maps audio features to phonemes.)"},
    {q:"Speaker diarization in the transcription playground refers to:",
     o:["Distinguishing which speaker said what",
        "Louder playback",
        "Emoji insertion",
        "Language translation"],
     a:0, d:2,
     x:"Diarization separates and labels different speakers in the audio — useful for meeting transcripts."},
    {q:"Language identification in speech transcription is used to:",
     o:["Detect which language is being spoken so the right recognition model applies",
        "Score grammar",
        "Encrypt audio",
        "Slow down playback"],
     a:0, d:2,
     x:"Language ID (at start or continuous) determines the spoken language for correct transcription."},
    {q:"For a notification service that reads alerts aloud on servers with no sound card, the synthesized audio should go to:",
     o:["A file output via an explicit AudioConfig",
        "The default speaker",
        "The microphone",
        "The tenant portal"],
     a:0, d:2,
     x:"With no speaker, configure AudioConfig for file (or stream) output rather than default speaker."},
    {q:"Which statement about the speech playground vs SDK is TRUE?",
     o:["Playground = interactive experimentation; SDK = integration into applications; both use the same underlying service",
        "The playground is required before every SDK call",
        "The SDK cannot transcribe files",
        "The playground writes production code automatically"],
     a:0, d:2,
     x:"They are two consumption modes of the same Azure Speech capabilities."},
    {q:"In Voice Live, 'background noise reduction' matters because:",
     o:["Real-world conversations happen in noisy environments and recognition quality would otherwise degrade",
        "It makes billing cheaper",
        "It converts noise into words",
        "It is required for JSON output"],
     a:0, d:2,
     x:"Noise robustness keeps continuous conversation usable outside quiet studios."},
    // ---- HARD (15) ----
    {q:"A caller says 'I want to recognize speech'. The system transcribes 'I want to wreck a nice beach'. Which two stages are involved in fixing this, and which is decisive?",
     o:["Acoustic model produces phonemes; the language model is decisive in selecting the probable word sequence",
        "Waveform encoding then prosody, prosody decisive",
        "Normalization then POS tagging, POS decisive",
        "Region detection then character classification, OCR decisive"],
     a:0, d:3,
     x:"The classic homophone example: phonemes are ambiguous; the language model must choose the statistically probable phrase."},
    {q:"Your STT code passes an endpoint but transcription always uses the microphone instead of the intended file. Which object was misconfigured?",
     o:["AudioConfig — it must specify filename to use a file source",
        "SpeechConfig — endpoints select files",
        "The synthesizer voice name",
        "The palette color"],
     a:0, d:3,
     x:"AudioConfig selects the audio source; without filename it defaults to the microphone."},
    {q:"Rank the correct SDK object construction order for file-based STT:",
     o:["SpeechConfig → AudioConfig → SpeechRecognizer → recognize_once_async()",
        "SpeechRecognizer → SpeechConfig → AudioConfig → get()",
        "AudioConfig → recognize → SpeechConfig → print",
        "recognize_once_async → SpeechRecognizer → SpeechConfig"],
     a:0, d:3,
     x:"Configure the service (SpeechConfig), the source (AudioConfig), build the recognizer, then invoke recognition."},
    {q:"A synthesized voice sounds robotic and flat with odd pauses. Which pipeline stage should be improved?",
     o:["Prosody generation — pitch, rhythm and timbre create natural cadence",
        "Audio capture",
        "Text region detection",
        "The language model of STT"],
     a:0, d:3,
     x:"Flat, unnatural cadence is a prosody problem — the stage responsible for natural-sounding articulation."},
    {q:"Why does the TTS pipeline normalize numbers BEFORE linguistic modeling, using '2026' as an example?",
     o:["'2026' must become words ('twenty twenty-six') so phoneme mapping has speakable input",
        "Numbers are removed from all speech",
        "Digits map to a single phoneme each",
        "Normalization happens last"],
     a:0, d:3,
     x:"Linguistic modeling maps words to phonemes; digits must first be expanded into their spoken word form."},
    {q:"A contact-center bot must let callers interrupt ('barge in') mid-answer, like a human agent. Which capability handles this natively?",
     o:["Voice Live — continuous conversation flow with interruption support",
        "Batch STT",
        "Playground screenshots",
        "AudioConfig file output"],
     a:0, d:3,
     x:"Interruption handling in continuous conversation is a core Voice Live feature."},
    {q:"Which claim about the Speech SDK is FALSE?",
     o:["It permanently archives all synthesized audio in Azure Storage automatically",
        "It authenticates using a key and endpoint",
        "It supports both microphone and file input",
        "It can output speech to the default speaker"],
     a:0, d:3,
     x:"The SDK does not auto-archive audio; storage is your application's responsibility."},
    {q:"A university records lectures and wants same-day searchable text plus spoken summaries for visually impaired students. Which capability pair applies?",
     o:["STT for transcription + TTS for spoken summaries",
        "TTS twice",
        "STT twice",
        "OCR + segmentation"],
     a:0, d:3,
     x:"Transcription is speech recognition; reading summaries aloud is speech synthesis — both accessibility use cases."},
    {q:"Voice Live sessions pair speech with 'a generative AI model that has instructions and tools'. What does this enable beyond plain transcription?",
     o:["The agent can reason about requests, follow its defined behavior, and act via tools — all by voice",
        "Higher audio sample rates",
        "Automatic invoicing",
        "GPU passthrough"],
     a:0, d:3,
     x:"Voice Live is agentic: the model reasons and acts (tools), with speech as the interface."},
    {q:"Which real-world factor does feature extraction (pre-processing) make recognition robust to?",
     o:["Variations in raw signal so the model sees consistent frequency-intensity features",
        "Different invoice layouts",
        "Font changes",
        "JSON schema drift"],
     a:0, d:3,
     x:"Featurization converts variable raw audio into normalized feature vectors the acoustic model can handle."},
    {q:"A demo needs the SAME sentence spoken in two different neural voices for comparison. What changes between the two runs?",
     o:["speech_config.speech_synthesis_voice_name",
        "The subscription key",
        "The resource group",
        "The recognizer object"],
     a:0, d:3,
     x:"The selected voice is a SpeechConfig property; the rest of the pipeline stays identical."},
    {q:"Which exam-style statement about STT vs TTS use cases is CORRECT?",
     o:["Customer-support call transcription is STT; reading chatbot replies aloud is TTS",
        "Both are TTS",
        "Both are STT",
        "Neither involves audio"],
     a:0, d:3,
     x:"Transcribing calls converts audio→text (STT); voicing replies converts text→audio (TTS)."},
    {q:"An app streams a caller's audio and needs partial results while they are still talking. Which recognition style is implied?",
     o:["Continuous/streaming recognition rather than single-shot recognize-once",
        "Batch overnight processing",
        "Manual typing",
        "Image OCR"],
     a:0, d:3,
     x:"recognize_once handles one utterance; streaming/continuous recognition delivers live partial results."},
    {q:"Why do STT systems post-process ('normalize and format') recognized text?",
     o:["Raw word sequences need punctuation, casing, and formatting to be readable ('nice to be here' → 'Nice to be here!')",
        "To re-add background noise",
        "To convert text back to phonemes",
        "To compress the transcript"],
     a:0, d:3,
     x:"Post-processing turns the raw predicted word sequence into clean, formatted text."},
    {q:"A team argues the playground alone is enough for their production IVR system. What is the STRONGEST counter-argument?",
     o:["Production systems must call the service from application code — that requires the SDK (or API), not a portal UI",
        "Playgrounds are usually offline",
        "Playgrounds cannot play audio",
        "IVR systems don't use speech"],
     a:0, d:3,
     x:"The playground is an experimentation surface; integration into applications requires the SDK/API."}
  ]
};
