window.BANKS = window.BANKS || {};
window.BANKS.q5a = {
  title: "Quiz 5A — Computer Vision",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Computer vision fundamentally analyzes and manipulates what kind of values?",
     o:["Pixels","File names","Timestamps in metadata","Folder paths"],
     a:0, d:1,
     x:"Vision works on pixel values — numeric representations of the image itself, not metadata."},
    {q:"Assigning a single label such as 'banana' to an entire image is called:",
     o:["Image classification","Object detection","Semantic segmentation","Prosody generation"],
     a:0, d:1,
     x:"Classification labels the whole image with one class."},
    {q:"Which vision task returns a bounding box and class for each object found?",
     o:["Object detection","Image classification","Contextual analysis","Tokenization"],
     a:0, d:1,
     x:"Object detection localizes each object with a box plus its class label."},
    {q:"Which task classifies every individual pixel in an image?",
     o:["Semantic segmentation","Image classification","Key-phrase extraction","Language detection"],
     a:0, d:1,
     x:"Semantic segmentation gives pixel-level classification — exact object outlines."},
    {q:"Producing the caption 'a person eating an apple' from a photo is an example of:",
     o:["Contextual image analysis","Stemming","Speaker diarization","Field mapping"],
     a:0, d:1,
     x:"Contextual image analysis describes the scene in natural language."},
    {q:"A model that can accept both an image and a text question in one prompt is called:",
     o:["Multimodal","Monolingual","Deterministic","Recursive"],
     a:0, d:1,
     x:"Multimodal models understand and work with more than one type of data, such as text and images."},
    {q:"Which model family generates images from text prompts?",
     o:["Diffusion models","Decision trees","Regression models","Bag-of-Words"],
     a:0, d:1,
     x:"Diffusion models power modern text-to-image generation."},
    {q:"In Foundry's catalog, which example model family handles video generation?",
     o:["sora models","gpt-image models","text-embedding models","whisper-like STT models"],
     a:0, d:1,
     x:"OpenAI sora models are the video-generation example; gpt-image models generate images."},
    // ---- MODERATE (7) ----
    {q:"What is the primary role of filters in a CNN used for image classification?",
     o:["Extracting numeric features from images for the neural network",
        "Applying cosmetic visual effects",
        "Compressing files for faster upload",
        "Encrypting the image"],
     a:0, d:2,
     x:"CNN filters extract feature maps — numeric features — that feed the fully connected layers."},
    {q:"Which description matches a Vision Transformer (ViT)?",
     o:["A model that uses attention over image patches to create contextual embeddings",
        "A tool that recolors images",
        "An agent that converts LLMs to vision models",
        "A codec for video compression"],
     a:0, d:2,
     x:"ViTs split images into patches, embed them, and apply attention to encode visual relationships."},
    {q:"What does a CNN output for a classification task?",
     o:["A probability for each class",
        "A bounding polygon per pixel",
        "A text summary",
        "An audio waveform"],
     a:0, d:2,
     x:"The final layer produces class probabilities; the highest probability is the prediction."},
    {q:"How is a diffusion model trained?",
     o:["By iteratively adding visual noise to labeled images and learning how the noise changes them",
        "By removing pixels until images vanish",
        "By ranking images alphabetically",
        "By transcribing image captions to audio"],
     a:0, d:2,
     x:"Training adds noise step-by-step to described images; generation reverses the process from random pixels."},
    {q:"In a multimodal prompt via the OpenAI API, images can be supplied as:",
     o:["URLs or base64-encoded data","Only local file paths","Only TIFF scans","Printed photographs"],
     a:0, d:2,
     x:"The content structure accepts image URLs or base64 data URIs."},
    {q:"Which content structure carries a multimodal request?",
     o:["A content array mixing input_text and input_image parts",
        "Two separate HTTP verbs",
        "A CSV with two columns",
        "An FTP upload"],
     a:0, d:2,
     x:"Multi-part prompts put text and image parts together in one message's content array."},
    {q:"Cross-modal attention in a ViT serves what purpose?",
     o:["Combining visual vector space with language vectors to create a multimodal model",
        "Sharpening blurry photos",
        "Reducing GPU memory",
        "Sorting images by size"],
     a:0, d:2,
     x:"Cross-modal attention aligns image and text embeddings so the model reasons across both."},
    // ---- HARD (15) ----
    {q:"A retailer needs to know WHERE each product sits on a shelf photo and WHAT each product is. Which task fits exactly?",
     o:["Object detection","Image classification","Contextual captioning","Language detection"],
     a:0, d:3,
     x:"Location (bounding box) + identity (class) per object = object detection. Classification would give one label for the whole photo."},
    {q:"A medical team needs tumor outlines precise to the pixel on scans. Which task do they need?",
     o:["Semantic segmentation","Object detection","Image classification","Key-phrase extraction"],
     a:0, d:3,
     x:"Pixel-exact boundaries require segmentation; detection only yields rectangular boxes."},
    {q:"Order the CNN classification flow correctly:",
     o:["Labeled images → filters extract features → feature maps flattened → fully connected network → class probabilities",
        "Class probabilities → filters → labels → flattening",
        "Flattening → labeling → filtering → probabilities → training",
        "Filters → probabilities → labeled images → flattening"],
     a:0, d:3,
     x:"Train on labeled images; filters produce feature maps; flatten; classify through dense layers; output per-class probabilities."},
    {q:"How does image GENERATION work at inference time with a diffusion model?",
     o:["Start from random pixels and iteratively remove learned noise guided by the description",
        "Copy the closest training image",
        "Ask a CNN to reverse-classify",
        "Sort noise alphabetically"],
     a:0, d:3,
     x:"Generation reverses the training process: denoise random pixels toward an image matching the prompt."},
    {q:"Why is sora video generation exposed as an asynchronous job?",
     o:["Video generation is resource-intensive and takes time, so you submit and poll rather than wait synchronously",
        "REST cannot return video",
        "Videos require user interaction during rendering",
        "Async is needed for JSON"],
     a:0, d:3,
     x:"Long-running, heavy workloads are modeled as async jobs — submit, then poll for completion."},
    {q:"How do developers programmatically generate images with a Foundry image model?",
     o:["Send text prompts through the OpenAI Responses API to the deployed image model",
        "Upload prompts via the portal UI only",
        "Call any chat model's endpoint",
        "Email the prompt to support"],
     a:0, d:3,
     x:"Image generation is programmatic via the Responses API against your deployed text-to-image model."},
    {q:"Which finding would tell you a model is NOT multimodal?",
     o:["It rejects prompts containing an input_image part and accepts only text",
        "It answers in French",
        "It runs in a project",
        "It has a system prompt"],
     a:0, d:3,
     x:"A text-only model can't consume image parts; multimodal models accept multiple input types."},
    {q:"A base64 data URI for a PNG in a multimodal prompt looks like:",
     o:["data:image/png;base64,<encoded-bytes>",
        "png://base64/data",
        "http://localhost/image.png.b64",
        "base64:image=png"],
     a:0, d:3,
     x:"The image_url field accepts either a normal URL or a data URI of the form data:image/png;base64,…"},
    {q:"To FIND image-generation models in the Foundry catalog, you should filter by:",
     o:["The 'text to image' inference task",
        "The provider's country",
        "Alphabetical order",
        "Price descending only"],
     a:0, d:3,
     x:"The catalog is filtered by inference task — 'text to image' for image generation, 'video generation' for video."},
    {q:"An inspection system must first decide IF a defect exists (whole image), and a second stage must outline the defect precisely. Which task pair is correct?",
     o:["Classification first, then semantic segmentation",
        "Segmentation first, then captioning",
        "Detection first, then classification of the whole image",
        "Captioning twice"],
     a:0, d:3,
     x:"Stage 1 is a whole-image yes/no (classification); stage 2 needs pixel-accurate outlines (segmentation)."},
    {q:"Which statement about ViTs vs CNNs is TRUE?",
     o:["ViTs process image patches with attention; CNNs slide filters to build feature maps",
        "CNNs use attention; ViTs use filters",
        "Both are identical internally",
        "ViTs cannot do classification"],
     a:0, d:3,
     x:"The architectures differ: convolutional filters vs patch embeddings + attention."},
    {q:"A user uploads a fridge photo and asks 'what can I cook?'. Which capability chain answers this?",
     o:["A multimodal model analyzes the image and reasons over the recognized items in one prompt",
        "OCR followed by TF-IDF",
        "STT followed by prosody",
        "A diffusion model denoises the fridge"],
     a:0, d:3,
     x:"Image-to-text inferencing with a multimodal model handles 'look at this image and answer' scenarios."},
    {q:"Why does contextual image analysis exceed plain classification for describing scenes?",
     o:["It produces a natural-language description capturing objects AND their relationships/actions",
        "It is always cheaper",
        "It ignores pixels",
        "It outputs bounding boxes only"],
     a:0, d:3,
     x:"Captions like 'a person eating an apple' encode relationships classification labels can't express."},
    {q:"In ViT step 1, patch embeddings are created from what raw material?",
     o:["Pixel values of each image patch","The EXIF metadata","The file's checksum","A text dictionary"],
     a:0, d:3,
     x:"Patches of the image are converted to embedding vectors from their pixel values."},
    {q:"A marketing team wants 30 original product-shot variations from one text brief, programmatically, plus one short teaser video. Which model/task pairing is correct?",
     o:["gpt-image ('text to image') via Responses API for stills; sora ('video generation') as async jobs for the teaser",
        "sora for stills; gpt-image for video",
        "A CNN classifier for both",
        "Azure Language for both"],
     a:0, d:3,
     x:"Stills = text-to-image models (gpt-image family); video = video-generation models (sora family), run asynchronously."}
  ]
};
