window.BANKS = window.BANKS || {};
window.BANKS.q5b = {
  title: "Quiz 5B — Computer Vision (round 2)",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Which vision task gives the LEAST granular output?",
     o:["Image classification (one label per image)",
        "Object detection",
        "Semantic segmentation",
        "They are equally granular"],
     a:0, d:1,
     x:"Classification labels the whole image; detection localizes objects; segmentation labels every pixel."},
    {q:"Detecting whether factory workers in CCTV footage wear helmets, and where they are, needs:",
     o:["Object detection","Sentiment analysis","Speech synthesis","TF-IDF"],
     a:0, d:1,
     x:"Locating and classifying people/helmets in frames is object detection."},
    {q:"A model producing an image from the prompt 'a lighthouse at sunset' is performing:",
     o:["Image generation","Image classification","OCR","Summarization"],
     a:0, d:1,
     x:"Text-to-image generation creates novel images from descriptions."},
    {q:"gpt-image models in the Foundry catalog belong to which inference task?",
     o:["Text to image","Video generation","Chat completion","Speech-to-text"],
     a:0, d:1,
     x:"gpt-image family models are text-to-image; sora models are video generation."},
    {q:"Which two data types does a typical multimodal vision prompt combine?",
     o:["Text and image","Audio and SQL","CSV and XML","Video and firmware"],
     a:0, d:1,
     x:"Image-to-text inferencing combines an input_text part with an input_image part."},
    {q:"What does 'base64-encoded' mean for an image in an API call?",
     o:["The binary image bytes are represented as text so they can travel inside JSON",
        "The image is reduced to 64 pixels",
        "The image is encrypted",
        "The image is split into 64 tiles"],
     a:0, d:1,
     x:"Base64 turns binary data into text characters — JSON-safe transport for the image bytes."},
    {q:"Which is an example of contextual image analysis output?",
     o:["'Two children playing football in a park'",
        "[0.98, 0.01, 0.01]",
        "A bounding box list",
        "A pixel mask"],
     a:0, d:1,
     x:"Contextual analysis yields a natural-language scene description."},
    {q:"Which statement about vision and pixels is TRUE?",
     o:["Vision algorithms compute over numeric pixel values",
        "Vision reads the picture's filename to decide content",
        "Vision needs printed photos",
        "Vision only works in grayscale"],
     a:0, d:1,
     x:"All vision techniques — CNNs, ViTs, diffusion — operate on pixel values."},
    // ---- MODERATE (7) ----
    {q:"In a CNN, what happens to feature maps before classification?",
     o:["They are flattened and passed to a fully connected network",
        "They are printed",
        "They are converted to phonemes",
        "They are emailed to the trainer"],
     a:0, d:2,
     x:"Flattening converts 2-D feature maps into a vector consumed by the dense layers that predict the class."},
    {q:"During CNN training, what data is required?",
     o:["Images with known labels","Unlabeled audio","Only text prompts","Spreadsheets of prices"],
     a:0, d:2,
     x:"Supervised classification training uses images paired with their known labels."},
    {q:"What is the FIRST step a ViT applies to an input image?",
     o:["Splitting it into patches that become embedding vectors",
        "Removing color",
        "Detecting text regions",
        "Adding noise"],
     a:0, d:2,
     x:"ViTs tile the image into patches, embedding each from its pixel values."},
    {q:"'The advances from ViTs let one model answer questions about pictures.' Which mechanism makes that possible?",
     o:["Cross-modal attention combining vision and language vector spaces",
        "Larger hard drives",
        "Anti-aliasing",
        "Batch normalization alone"],
     a:0, d:2,
     x:"Cross-modal attention aligns visual and language embeddings into one multimodal space."},
    {q:"A generated image slowly 'emerges' from static-like noise during creation. Which model behavior is being observed?",
     o:["Diffusion denoising steps","CNN flattening","Bag-of-Words","Beam search"],
     a:0, d:2,
     x:"Diffusion generation iteratively removes noise, so intermediate steps look like progressively cleaner images."},
    {q:"Which API field carries the picture in an OpenAI multimodal request?",
     o:["image_url inside an input_image content part",
        "audio_config",
        "system_fingerprint",
        "stop_sequences"],
     a:0, d:2,
     x:"The input_image content part holds an image_url (real URL or data URI)."},
    {q:"Which task/scenario pairing is WRONG?",
     o:["Semantic segmentation — counting how many total images are cats",
        "Object detection — locating cars in a parking lot photo",
        "Classification — deciding if an X-ray is normal or abnormal",
        "Contextual analysis — describing a holiday photo"],
     a:0, d:2,
     x:"Counting images by overall content is classification applied per image; segmentation is pixel-level labeling."},
    // ---- HARD (15) ----
    {q:"An autonomous drone must distinguish road, grass, and water for EVERY point in view to plan landing. Which task and why?",
     o:["Semantic segmentation — pixel-level class map of the scene",
        "Classification — one label suffices",
        "Detection — boxes are enough",
        "Captioning — text description is enough"],
     a:0, d:3,
     x:"Safe landing requires knowing the class of every pixel — segmentation, not boxes or single labels."},
    {q:"Why can't a plain image CLASSIFIER count the apples in a crate photo?",
     o:["It outputs one label for the whole image; counting needs per-object localization (detection)",
        "Apples cannot be classified",
        "Classifiers only work on video",
        "Counting requires audio"],
     a:0, d:3,
     x:"Counting requires finding each instance — object detection; classification collapses the image to one label."},
    {q:"Your multimodal request fails: the content array has an input_text part but the picture was pasted as raw binary into the JSON. What is the fix?",
     o:["Encode the image as base64 (data URI) or host it and pass a URL",
        "Rename the file to .txt",
        "Use FTP",
        "Add more text parts"],
     a:0, d:3,
     x:"JSON can't carry raw binary — supply the image as a base64 data URI or a fetchable URL."},
    {q:"Rank the diffusion TRAINING process correctly:",
     o:["Take labeled images → add noise step-by-step → learn how noise changes images given their descriptions",
        "Generate random pixels → classify → label",
        "Remove noise from clean images → save weights",
        "Sort images → flatten → caption"],
     a:0, d:3,
     x:"Training corrupts described images progressively with noise so the model learns the noise process to reverse later."},
    {q:"A video-generation job was submitted 10 seconds ago and the client blocks waiting for the MP4 in the HTTP response. What is wrong?",
     o:["Video jobs are asynchronous — the client should poll the job status until complete",
        "Videos must be requested by email",
        "The MP4 arrives via DNS",
        "Nothing — sora responds instantly"],
     a:0, d:3,
     x:"Resource-intensive video generation is a submit-then-poll workflow, not a synchronous call."},
    {q:"Which capability list belongs to MULTIMODAL models (vs single-modality)?",
     o:["Answering questions about an uploaded photo, captioning scenes, reasoning over image + text together",
        "Only transcribing audio",
        "Only tokenizing text",
        "Only compressing files"],
     a:0, d:3,
     x:"Multimodal models reason across data types — image+text prompts, captions, visual Q&A."},
    {q:"A quality-control lead asks why the CNN reports 'defect: 0.83'. What does the number represent?",
     o:["The predicted probability for the 'defect' class from the network's output layer",
        "83 defects were found",
        "83% of pixels are dark",
        "The image is 83% compressed"],
     a:0, d:3,
     x:"CNN classifiers output per-class probabilities; 0.83 is the model's confidence in the 'defect' class."},
    {q:"Which pipeline choice matches 'generate marketing stills programmatically at scale'?",
     o:["Deploy a text-to-image model and call it via the OpenAI Responses API from code",
        "Manually use the playground for each image",
        "Train a CNN from scratch",
        "Use the speech SDK"],
     a:0, d:3,
     x:"Scale = code: deployed image model + Responses API. The playground is manual experimentation."},
    {q:"An exam item asks the difference between DETECTION output and SEGMENTATION output for the same street photo. Correct answer:",
     o:["Detection: labeled bounding boxes per object; segmentation: a class for every pixel including exact outlines",
        "They output identical structures",
        "Detection outputs pixel masks; segmentation outputs boxes",
        "Both output captions"],
     a:0, d:3,
     x:"Boxes vs pixel masks is the canonical distinction."},
    {q:"Which factor explains why ViT-based multimodal models emerged AFTER text transformers?",
     o:["The transformer's attention mechanism was extended from language tokens to image patches, then linked across modalities",
        "Cameras were invented later",
        "Pixels were only standardized recently",
        "CNNs banned attention"],
     a:0, d:3,
     x:"ViTs adapt the proven attention architecture to vision, and cross-modal attention then unifies the two spaces."},
    {q:"A teacher uploads a hand-drawn physics diagram and asks the model to explain the forces shown. Which THREE capabilities combine?",
     o:["Multimodal image understanding, language reasoning, and generation of an explanatory answer",
        "OCR, FTP, and DNS",
        "Segmentation, diarization, and prosody",
        "Detection, invoicing, and tagging"],
     a:0, d:3,
     x:"Visual understanding + reasoning + text generation is the multimodal Q&A pattern."},
    {q:"Why might a team choose an image URL over base64 in production prompts?",
     o:["URLs keep request payloads small; base64 inflates the JSON body size",
        "URLs are more colorful",
        "Base64 is deprecated",
        "URLs bypass authentication"],
     a:0, d:3,
     x:"Base64 encoding grows payloads ~33%; hosting the image and passing a URL keeps requests lean."},
    {q:"An image-generation deployment must NOT produce photorealistic images of real politicians. Where should this restriction live?",
     o:["In the deployment's guardrails (responsible AI policies), reinforced by app-level checks",
        "In the resource group name",
        "In the billing tier",
        "In the temperature parameter"],
     a:0, d:3,
     x:"Content restrictions are enforced through responsible-AI guardrails on the deployment, plus application safeguards."},
    {q:"Which statement about image generation randomness is TRUE?",
     o:["The same prompt can yield different images because generation starts from random noise",
        "The same prompt always yields the identical image",
        "Randomness comes from the file name",
        "Only videos are random"],
     a:0, d:3,
     x:"Diffusion starts from random pixels, so each run of the same prompt can produce a different valid image."},
    {q:"A museum app should let visitors photograph any exhibit and receive an engaging spoken description. Chain the correct capabilities in order:",
     o:["Multimodal image analysis → text description → text-to-speech audio",
        "TTS → STT → OCR",
        "Segmentation → invoicing → detection",
        "Diffusion → denoising → classification"],
     a:0, d:3,
     x:"Understand the photo (multimodal), generate the description (text), then voice it (TTS)."}
  ]
};
