window.BANKS = window.BANKS || {};
window.BANKS.q6a = {
  title: "Quiz 6A — Information Extraction",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Which statement accurately defines AI information extraction?",
     o:["Analyzing unstructured content to identify and extract relevant fields and values",
        "Running SQL queries against a database",
        "Copying files from cloud storage to a laptop",
        "Compressing PDF files"],
     a:0, d:1,
     x:"Information extraction converts unstructured digital content — documents, images, audio, video — into useful structured data."},
    {q:"OCR stands for:",
     o:["Optical character recognition","Online content retrieval","Open conversion routine","Operational cache register"],
     a:0, d:1,
     x:"Optical character recognition converts images of text into machine-readable text data."},
    {q:"Which content types can information extraction process?",
     o:["Documents, receipts, invoices, images, audio, and video",
        "Only spreadsheets",
        "Only plain-text files",
        "Only web pages"],
     a:0, d:1,
     x:"Extraction spans documents, emails, business cards, receipts, invoices, contracts, images, audio recordings, and video."},
    {q:"Reading the vendor name, date, and total from a photographed receipt to pre-fill an expense claim is an example of:",
     o:["Information extraction","Speech synthesis","Semantic segmentation","Temperature tuning"],
     a:0, d:1,
     x:"The receipt-to-expense-claim scenario is the classic information-extraction example."},
    {q:"Which Foundry service specializes in extracting structured data from documents and media?",
     o:["Azure Content Understanding in Foundry Tools",
        "Azure DNS",
        "Azure Load Balancer",
        "Azure Backup"],
     a:0, d:1,
     x:"Azure Content Understanding is Foundry's information-extraction service with predefined and custom analyzers."},
    {q:"In Content Understanding, what is an analyzer?",
     o:["The definition of how content is processed and what structured data is returned",
        "A person who reviews documents",
        "A GPU monitoring tool",
        "A file-compression utility"],
     a:0, d:1,
     x:"Analyzers define processing behavior and the output schema — predefined for common documents or custom from samples."},
    {q:"In what format does the Content Understanding REST API return results?",
     o:["JSON","MP3","BMP","ZIP"],
     a:0, d:1,
     x:"Analyzer results are retrieved as JSON via the REST API."},
    {q:"Which is a predefined-analyzer scenario for common business documents?",
     o:["Invoice data extraction","Video game rendering","Firewall configuration","Wi-Fi optimization"],
     a:0, d:1,
     x:"Predefined analyzers cover common documents and forms such as invoices, receipts, and contracts."},
    // ---- MODERATE (7) ----
    {q:"Order the OCR pipeline correctly:",
     o:["Image acquisition → pre-processing → text region detection → character recognition → output generation",
        "Character recognition → acquisition → detection → output → pre-processing",
        "Output → detection → acquisition → recognition → enhancement",
        "Detection → output → acquisition → enhancement → recognition"],
     a:0, d:2,
     x:"Acquire the image, enhance it, find text regions, recognize/classify characters, then produce post-processed output."},
    {q:"After OCR, which process attaches recognized values to meaningful business fields?",
     o:["Field extraction and mapping","Prosody generation","Tokenization","Stemming"],
     a:0, d:2,
     x:"Field extraction/mapping detects candidate values and associates them with schema fields."},
    {q:"What does data normalization do in the extraction pipeline?",
     o:["Standardizes formats — e.g., $20 → 20.00 and 01/01/2025 → 2025-01-01",
        "Deletes all numbers",
        "Adds random noise",
        "Translates the document"],
     a:0, d:2,
     x:"Normalization standardizes extracted values so downstream systems receive consistent formats."},
    {q:"How does generative AI enhance field mapping?",
     o:["Semantic language models match extracted values to data fields accurately, replacing hand-coded rules per document type",
        "It generates new invoices from scratch",
        "It photocopies documents faster",
        "It removes the need for OCR input"],
     a:0, d:2,
     x:"Semantic understanding lets the mapper handle layout variations without manually coded rules for each document type."},
    {q:"Which audio/video scenarios does Content Understanding support?",
     o:["Post-call analysis, voice-message automation, video transcription and summary, recording analysis",
        "Live concert mixing",
        "Codec development",
        "Ringtone composition"],
     a:0, d:2,
     x:"Predefined and custom analyzers cover post-call analysis, voice messages, video call transcription/summary, and recording analysis."},
    {q:"How is a CUSTOM analyzer created?",
     o:["By defining a schema based on sample documents",
        "By emailing Microsoft support",
        "By retraining GPT from scratch",
        "By exporting a firewall rule"],
     a:0, d:2,
     x:"You define your own schema from sample content; the analyzer then extracts those fields from new documents."},
    {q:"With the Content Understanding Python SDK, what happens after you submit content?",
     o:["You poll a URL until the analysis job completes",
        "Results return instantly in the same response",
        "The analyzer retrains itself",
        "The content is printed"],
     a:0, d:2,
     x:"Analysis is asynchronous — submit, then poll the operation until it completes and fetch the JSON results."},
    // ---- HARD (15) ----
    {q:"What is the KEY advantage of Azure Content Understanding over basic OCR?",
     o:["It understands document structure and maps extracted data to a defined schema",
        "It skips image pre-processing for speed",
        "It produces prettier fonts",
        "It only works on typed text"],
     a:0, d:3,
     x:"OCR reads text; Content Understanding adds structural understanding and schema mapping with confidence scores."},
    {q:"A logistics firm receives delivery notes from 200 suppliers, each with different layouts. Hand-coded extraction rules keep breaking. Which approach fixes the root problem?",
     o:["A semantic, generative-AI-assisted analyzer that maps values to schema fields regardless of layout",
        "More regex rules per supplier",
        "Asking suppliers to fax instead",
        "Manual data entry"],
     a:0, d:3,
     x:"Semantic field mapping generalizes across layouts — the documented advantage of generative AI in extraction."},
    {q:"Which output would you expect from a predefined invoice analyzer?",
     o:["JSON fields like CustomerName, InvoiceDate, InvoiceId with confidence scores",
        "A rendered 3D invoice",
        "An MP3 narration",
        "A trained model file"],
     a:0, d:3,
     x:"Predefined analyzers return schema-mapped fields (with per-field confidence) as JSON."},
    {q:"A scanned page is skewed and low-contrast, and OCR accuracy suffers. Which pipeline stage addresses this?",
     o:["Pre-processing and image enhancement","Field mapping","Output generation","Post-call analysis"],
     a:0, d:3,
     x:"Deskewing, denoising, and contrast enhancement happen in OCR pre-processing."},
    {q:"Why does OCR include a text REGION detection step before recognizing characters?",
     o:["Locating text areas first avoids wasting recognition on graphics/background and preserves layout structure",
        "Regions are needed for billing",
        "Characters cannot exist outside regions",
        "It converts text to speech"],
     a:0, d:3,
     x:"Region detection isolates where text lives so character recognition runs only there and layout is retained."},
    {q:"Which statement correctly contrasts OCR output and field-mapped output for '01/01/2025 … total $20'?",
     o:["OCR yields raw text tokens; field mapping yields Date=2025-01-01 and Amount=20.00 bound to schema fields",
        "OCR yields normalized fields; mapping yields raw pixels",
        "Both yield identical structures",
        "Neither yields text"],
     a:0, d:3,
     x:"OCR gives text; extraction/mapping/normalization turn it into typed, standardized fields."},
    {q:"A contact center wants each call summarized with topics, companies mentioned, and speaker breakdown. Which Content Understanding scenario is this?",
     o:["Post-call analysis with an audio analyzer",
        "Invoice extraction",
        "Image classification",
        "Text-to-speech"],
     a:0, d:3,
     x:"Post-call analysis applies an audio analyzer to produce transcripts, summaries, topics, and entities."},
    {q:"'The results are returned immediately in the same request' — why is this WRONG for the Content Understanding SDK?",
     o:["Analysis is a long-running job; the SDK submits it and you poll the result URL until completion",
        "Results arrive by post",
        "The SDK never returns results",
        "It is actually correct"],
     a:0, d:3,
     x:"Content analysis is asynchronous by design — submit, poll, then read the completed JSON."},
    {q:"Which choice lists the field-extraction pipeline in the right order?",
     o:["OCR ingestion → field detection → field mapping → normalization → integration with business systems",
        "Integration → OCR → normalization → detection → mapping",
        "Mapping → OCR → integration → detection → normalization",
        "Normalization → integration → OCR → mapping → detection"],
     a:0, d:3,
     x:"Ingest recognized text, detect candidate values, map to schema, normalize formats, then integrate."},
    {q:"An exam distractor claims OCR means 'Online Content Retrieval used to copy cloud data locally.' Identify the error:",
     o:["OCR is optical character recognition — converting images of text into machine-readable text",
        "The definition is correct",
        "OCR is Open Conversion Routine for JSON→image",
        "OCR is a network protocol"],
     a:0, d:3,
     x:"Watch for plausible-sounding expansions; OCR = optical character recognition."},
    {q:"A firm needs contract clauses (parties, term, renewal date) pulled from legal PDFs into their CLM system. Map the correct solution stack:",
     o:["Content Understanding analyzer (predefined contract or custom schema) → JSON via REST → CLM integration",
        "Speech SDK → WAV → CLM",
        "Diffusion model → PNG → CLM",
        "Playground screenshots → email"],
     a:0, d:3,
     x:"Document analyzers extract schema fields as JSON, which integrates with business systems."},
    {q:"Why do analyzers attach a CONFIDENCE score to each extracted field?",
     o:["So downstream processes can route low-confidence values to human review",
        "To rank vendors",
        "To measure GPU heat",
        "Scores are decorative"],
     a:0, d:3,
     x:"Confidence enables human-in-the-loop workflows — auto-accept high confidence, review low confidence."},
    {q:"Which requirement clearly needs a CUSTOM analyzer rather than a predefined one?",
     o:["Extracting fields unique to your company's proprietary inspection form",
        "Reading a standard sales invoice",
        "Reading a typical retail receipt",
        "Post-call transcript summary"],
     a:0, d:3,
     x:"Proprietary layouts/fields aren't covered by predefined analyzers — define a custom schema from samples."},
    {q:"A voicemail system should transcribe messages, extract callback numbers and reasons, and create tickets automatically. Which scenario name fits?",
     o:["Voice-message automation using an audio analyzer",
        "Semantic segmentation",
        "Image generation",
        "Stop-word removal"],
     a:0, d:3,
     x:"Voice-message automation is a listed audio scenario for Content Understanding."},
    {q:"What is the correct division of labor: OCR vs analyzer vs business system?",
     o:["OCR reads text; the analyzer structures it against a schema; the business system consumes the JSON",
        "The analyzer reads pixels; OCR does schemas; JSON prints invoices",
        "The business system does OCR",
        "All three are the same component"],
     a:0, d:3,
     x:"Reading, structuring, and consuming are distinct stages — OCR → analyzer schema mapping → integration."}
  ]
};
