window.BANKS = window.BANKS || {};
window.BANKS.q6b = {
  title: "Quiz 6B — Information Extraction (round 2)",
  minutes: 30,
  questions: [
    // ---- EASY (8) ----
    {q:"Information extraction is best summarized as converting digital content into:",
     o:["Useful, structured data","Compressed archives","Encrypted blobs","Printed booklets"],
     a:0, d:1,
     x:"The goal is turning unstructured content (documents, media) into structured, actionable data."},
    {q:"What does OCR produce from a photo of a printed page?",
     o:["Machine-readable text","A higher-resolution photo","An audio narration","A vector logo"],
     a:0, d:1,
     x:"OCR converts images of text into machine-readable text data."},
    {q:"Which pair belongs to the SAME workload?",
     o:["Receipt field extraction and contract clause extraction",
        "Receipt extraction and text-to-speech",
        "Contract extraction and image generation",
        "OCR and prosody"],
     a:0, d:1,
     x:"Both extract structured fields from documents — information extraction."},
    {q:"Which item is NOT a typical information-extraction source?",
     o:["A GPU driver installer","A scanned invoice","A recorded support call","A business card photo"],
     a:0, d:1,
     x:"Extraction sources are content: documents, forms, images, audio, video — not software installers."},
    {q:"Predefined analyzers exist for which common items?",
     o:["Invoices, receipts, and contracts","Firewall rules","DNS zones","CSS stylesheets"],
     a:0, d:1,
     x:"Content Understanding ships predefined analyzers for common documents and forms."},
    {q:"Results from an analyzer are retrieved using which interface?",
     o:["The REST API (JSON results)","A COM port","A USB cable","A fax gateway"],
     a:0, d:1,
     x:"You call the REST API (or SDK wrapper) and receive JSON results."},
    {q:"Transcribing and summarizing a recorded video call is handled by:",
     o:["An audio/video analyzer in Content Understanding","A CNN classifier","A stop-word filter","A resource lock"],
     a:0, d:1,
     x:"Video call transcription and summary is a listed audio/video analyzer scenario."},
    {q:"The last stage of field extraction feeds data into:",
     o:["Business processes and systems","The GPU fan","The DNS resolver","The image sensor"],
     a:0, d:1,
     x:"Extraction ends with integration — structured values flowing into business systems."},
    // ---- MODERATE (7) ----
    {q:"Which OCR stage classifies the individual characters found in text regions?",
     o:["Character recognition and classification","Image acquisition","Field normalization","Post-call analysis"],
     a:0, d:2,
     x:"After regions are detected, character recognition identifies and classifies the characters and words."},
    {q:"'$20' becoming '20.00' and '01/01/2025' becoming '2025-01-01' happens during:",
     o:["Data normalization and standardization","Text region detection","Image acquisition","Speaker diarization"],
     a:0, d:2,
     x:"Normalization standardizes value formats for downstream systems."},
    {q:"Field DETECTION differs from field MAPPING how?",
     o:["Detection finds candidate values; mapping associates each value with the right schema field",
        "Detection prints; mapping scans",
        "They are identical",
        "Mapping happens before OCR"],
     a:0, d:2,
     x:"First candidates are identified (dates, totals, names), then each is bound to its schema field."},
    {q:"To build an analyzer for your company's unique lab-report format, you would:",
     o:["Define a custom schema based on sample lab reports",
        "Use the predefined receipt analyzer unchanged",
        "Convert reports to MP3",
        "Lower the temperature"],
     a:0, d:2,
     x:"Custom analyzers are created by defining a schema from your own sample documents."},
    {q:"Which benefit does schema mapping give an expense system consuming receipt data?",
     o:["It can rely on consistent field names/types (Vendor, Date, Amount) regardless of receipt layout",
        "It makes receipts prettier",
        "It eliminates all taxes",
        "It removes the need for storage"],
     a:0, d:2,
     x:"Schema-mapped output is stable and typed, so integrations don't depend on each receipt's layout."},
    {q:"For a batch of 10,000 scanned forms, why is the asynchronous submit-and-poll model appropriate?",
     o:["Analysis is long-running at scale; async jobs let clients continue and collect results when ready",
        "Polling is decorative",
        "Synchronous calls are illegal",
        "JSON requires polling"],
     a:0, d:2,
     x:"Long-running batch analysis fits the async pattern — submit jobs, poll for completion."},
    {q:"Which statement about audio analyzers is TRUE?",
     o:["They can produce transcripts plus structured fields like summary, topics, and people mentioned",
        "They only measure volume",
        "They convert audio to invoices",
        "They require video input"],
     a:0, d:2,
     x:"Audio analyzers output transcripts and schema fields (summary, topics, companies, people) from recordings."},
    // ---- HARD (15) ----
    {q:"A scanned contract produces perfect OCR text, but the system still can't tell WHICH date is the renewal date. What is missing?",
     o:["Field extraction and mapping against a schema — OCR alone has no semantic understanding",
        "A better camera",
        "Higher DPI",
        "A louder microphone"],
     a:0, d:3,
     x:"OCR reads text; identifying which value plays which business role requires field mapping to a schema."},
    {q:"Rank the FULL journey of a paper receipt to an ERP entry:",
     o:["Photo → OCR pipeline → field detection/mapping → normalization → JSON via API → ERP integration",
        "ERP → JSON → OCR → photo",
        "Normalization → photo → ERP → OCR",
        "Photo → ERP → OCR → JSON"],
     a:0, d:3,
     x:"Capture, read (OCR), structure (mapping), standardize (normalization), then integrate via the API's JSON."},
    {q:"Your custom analyzer returns 'InvoiceTotal' at 0.42 confidence for some suppliers. What is the BEST operational response?",
     o:["Route low-confidence extractions to human review while auto-accepting high-confidence ones",
        "Ignore confidence entirely",
        "Reject all documents",
        "Multiply the value by the confidence"],
     a:0, d:3,
     x:"Confidence thresholds enable a human-in-the-loop pattern — the reason scores are provided."},
    {q:"Which scenario is NOT information extraction?",
     o:["Generating a fictional invoice image from a text prompt",
        "Pulling PO numbers from supplier PDFs",
        "Summarizing topics from a recorded call",
        "Reading fields from ID cards"],
     a:0, d:3,
     x:"Creating new content is generative AI. Extraction pulls structured data OUT of existing content."},
    {q:"A team asks whether to use Azure Content Understanding or plain OCR + custom code. Which factor argues for Content Understanding?",
     o:["Built-in schema mapping with confidence scores and predefined analyzers reduce custom engineering",
        "OCR licenses are illegal",
        "Custom code is always faster to build",
        "Content Understanding works offline only"],
     a:0, d:3,
     x:"The service's structural understanding + schema mapping is precisely what you'd otherwise hand-build."},
    {q:"An insurer processes claim forms, damage photos, AND recorded claim calls. Which capability claim about Content Understanding is accurate?",
     o:["Analyzers cover documents, images, audio, and video — one service can structure all three inputs",
        "It handles documents only",
        "It handles audio only",
        "Photos require a separate tenant"],
     a:0, d:3,
     x:"Content Understanding spans documents and media — analyzers exist for document, audio, and video scenarios."},
    {q:"During polling, the analysis job status is 'running'. What should the client do?",
     o:["Wait and poll again until the status indicates completion, then fetch results",
        "Resubmit the same content immediately",
        "Delete the analyzer",
        "Switch to synchronous mode"],
     a:0, d:3,
     x:"Async pattern: keep polling until completion; resubmitting duplicates work."},
    {q:"Which pre-processing failure mode most hurts region DETECTION (not recognition)?",
     o:["Severe page skew making text lines hard to localize",
        "A single ambiguous character",
        "An unusual font for one word",
        "A misspelled word"],
     a:0, d:3,
     x:"Skew disrupts locating text areas; single-character issues affect recognition, not region detection."},
    {q:"Map each item to its pipeline: (1) deskewing, (2) matching '20.00' to the Amount field, (3) ISO date formatting.",
     o:["1 = OCR pre-processing; 2 = field mapping; 3 = normalization",
        "1 = normalization; 2 = OCR; 3 = mapping",
        "1 = mapping; 2 = deskewing; 3 = OCR",
        "All three are OCR"],
     a:0, d:3,
     x:"Image cleanup is OCR pre-processing; associating values to fields is mapping; standardizing formats is normalization."},
    {q:"Why does generative-AI-based field matching generalize better than rule-based matching?",
     o:["Semantic models understand that 'Amt Due', 'Total Payable' and 'Balance' can all mean the invoice total",
        "It memorizes every layout on Earth",
        "Rules are faster so they generalize worse",
        "It doesn't — rules always win"],
     a:0, d:3,
     x:"Semantic equivalence across varied labels/layouts is what language models capture and rules miss."},
    {q:"A predefined receipt analyzer works well, but your receipts include a company-specific 'CostCenter' code it never returns. Best path forward?",
     o:["Create a custom analyzer whose schema includes CostCenter, trained from sample receipts",
        "Ask staff to memorize codes",
        "Use the speech playground",
        "Turn confidence off"],
     a:0, d:3,
     x:"Fields outside the predefined schema call for a custom analyzer defined from your samples."},
    {q:"Which statement about the relationship between information extraction and NLP is MOST accurate?",
     o:["Extraction often uses NLP techniques (like NER) on recognized text to identify field values",
        "They are unrelated workloads",
        "NLP replaces OCR",
        "Extraction only works on audio"],
     a:0, d:3,
     x:"After OCR, entity recognition and other NLP techniques help identify and classify candidate values."},
    {q:"An auditor wants evidence of WHERE on the page each extracted value was found. Which OCR/analyzer output supports this?",
     o:["Positional/layout information (regions, offsets) returned with recognized text",
        "The document's file size",
        "The GPU model used",
        "The analyst's name"],
     a:0, d:3,
     x:"OCR output includes text positions; analyzers preserve source location so values are traceable to page regions."},
    {q:"Video recording analysis of a training session should yield chapter summaries and key topics. Which analyzer characteristics make this possible?",
     o:["Analyzers define a schema of fields (summary, topics) generated from the video's transcript and content",
        "Analyzers edit the video",
        "Analyzers upscale resolution",
        "Analyzers require live streams"],
     a:0, d:3,
     x:"Custom/predefined video analyzers return schema fields derived from transcript + content analysis."},
    {q:"Which end-to-end design correctly automates supplier-invoice intake with LOW manual effort and HIGH auditability?",
     o:["Invoice analyzer with schema mapping → confidence-based human review queue → normalized JSON into the ERP",
        "Manual typing with no logs",
        "Screenshot each invoice into a chat model with no structure",
        "Store PDFs unprocessed"],
     a:0, d:3,
     x:"Schema mapping automates structure, confidence routing preserves accuracy, and JSON integration completes the flow."}
  ]
};
